import type { Metadata } from "next";
import ThemeProvider from "@/components/ThemeProvider";
import Header from "@/components/Header";
import Providers from "./providers";
import AuthErrorModal from "@/features/auth/components/AuthErrorModal";
import { Inter } from "next/font/google";
import 'react-datepicker/dist/react-datepicker.css';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="ja"
      suppressHydrationWarning
    >
      <body className={inter.className}>
        <Providers>
          <ThemeProvider
            defaultTheme="system"
            enableSystem
          >
            <Header />
            {children}
            <AuthErrorModal />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
