FROM golang:1.26-bookworm

WORKDIR /backend

# 必要なツールのインストール
RUN go install github.com/air-verse/air@latest

# ローカルのファイルをコンテナにコピー
COPY . .

# モジュールのダウンロード
RUN go mod download

# ポートの公開
EXPOSE 8080

# コンテナ起動時のコマンド
CMD ["air"]