// Code generated by ent, DO NOT EDIT.

package event

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the event type in the database.
	Label = "event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPrimaryCalendarID holds the string denoting the primary_calendar_id field in the database.
	FieldPrimaryCalendarID = "primary_calendar_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldConfirmedDateID holds the string denoting the confirmed_date_id field in the database.
	FieldConfirmedDateID = "confirmed_date_id"
	// FieldGoogleEventID holds the string denoting the google_event_id field in the database.
	FieldGoogleEventID = "google_event_id"
	// FieldConfirmedGoogleEventID holds the string denoting the confirmed_google_event_id field in the database.
	FieldConfirmedGoogleEventID = "confirmed_google_event_id"
	// FieldSyncStatus holds the string denoting the sync_status field in the database.
	FieldSyncStatus = "sync_status"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// FieldLastSyncError holds the string denoting the last_sync_error field in the database.
	FieldLastSyncError = "last_sync_error"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgePrimaryCalendar holds the string denoting the primary_calendar edge name in mutations.
	EdgePrimaryCalendar = "primary_calendar"
	// EdgeConfirmedDate holds the string denoting the confirmed_date edge name in mutations.
	EdgeConfirmedDate = "confirmed_date"
	// EdgeProposedDates holds the string denoting the proposed_dates edge name in mutations.
	EdgeProposedDates = "proposed_dates"
	// Table holds the table name of the event in the database.
	Table = "events"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "events"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// PrimaryCalendarTable is the table that holds the primary_calendar relation/edge.
	PrimaryCalendarTable = "events"
	// PrimaryCalendarInverseTable is the table name for the Calendar entity.
	// It exists in this package in order to avoid circular dependency with the "calendar" package.
	PrimaryCalendarInverseTable = "calendars"
	// PrimaryCalendarColumn is the table column denoting the primary_calendar relation/edge.
	PrimaryCalendarColumn = "primary_calendar_id"
	// ConfirmedDateTable is the table that holds the confirmed_date relation/edge.
	ConfirmedDateTable = "events"
	// ConfirmedDateInverseTable is the table name for the ProposedDate entity.
	// It exists in this package in order to avoid circular dependency with the "proposeddate" package.
	ConfirmedDateInverseTable = "proposed_dates"
	// ConfirmedDateColumn is the table column denoting the confirmed_date relation/edge.
	ConfirmedDateColumn = "confirmed_date_id"
	// ProposedDatesTable is the table that holds the proposed_dates relation/edge.
	ProposedDatesTable = "proposed_dates"
	// ProposedDatesInverseTable is the table name for the ProposedDate entity.
	// It exists in this package in order to avoid circular dependency with the "proposeddate" package.
	ProposedDatesInverseTable = "proposed_dates"
	// ProposedDatesColumn is the table column denoting the proposed_dates relation/edge.
	ProposedDatesColumn = "event_id"
)

// Columns holds all SQL columns for event fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldUserID,
	FieldPrimaryCalendarID,
	FieldTitle,
	FieldDescription,
	FieldLocation,
	FieldStatus,
	FieldConfirmedDateID,
	FieldGoogleEventID,
	FieldConfirmedGoogleEventID,
	FieldSyncStatus,
	FieldLastSyncedAt,
	FieldLastSyncError,
	FieldSlug,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "events"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"calendar_events",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/koo-arch/adjusta-backend/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusDraft     Status = "draft"
	StatusActive    Status = "active"
	StatusConfirmed Status = "confirmed"
	StatusCancelled Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDraft, StatusActive, StatusConfirmed, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("event: invalid enum value for status field: %q", s)
	}
}

// SyncStatus defines the type for the "sync_status" enum field.
type SyncStatus string

// SyncStatusNotSynced is the default value of the SyncStatus enum.
const DefaultSyncStatus = SyncStatusNotSynced

// SyncStatus values.
const (
	SyncStatusNotSynced   SyncStatus = "not_synced"
	SyncStatusPendingSync SyncStatus = "pending_sync"
	SyncStatusSynced      SyncStatus = "synced"
	SyncStatusSyncFailed  SyncStatus = "sync_failed"
)

func (ss SyncStatus) String() string {
	return string(ss)
}

// SyncStatusValidator is a validator for the "sync_status" field enum values. It is called by the builders before save.
func SyncStatusValidator(ss SyncStatus) error {
	switch ss {
	case SyncStatusNotSynced, SyncStatusPendingSync, SyncStatusSynced, SyncStatusSyncFailed:
		return nil
	default:
		return fmt.Errorf("event: invalid enum value for sync_status field: %q", ss)
	}
}

// OrderOption defines the ordering options for the Event queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPrimaryCalendarID orders the results by the primary_calendar_id field.
func ByPrimaryCalendarID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrimaryCalendarID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByConfirmedDateID orders the results by the confirmed_date_id field.
func ByConfirmedDateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedDateID, opts...).ToFunc()
}

// ByGoogleEventID orders the results by the google_event_id field.
func ByGoogleEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoogleEventID, opts...).ToFunc()
}

// ByConfirmedGoogleEventID orders the results by the confirmed_google_event_id field.
func ByConfirmedGoogleEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfirmedGoogleEventID, opts...).ToFunc()
}

// BySyncStatus orders the results by the sync_status field.
func BySyncStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncStatus, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByLastSyncError orders the results by the last_sync_error field.
func ByLastSyncError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncError, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByPrimaryCalendarField orders the results by primary_calendar field.
func ByPrimaryCalendarField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrimaryCalendarStep(), sql.OrderByField(field, opts...))
	}
}

// ByConfirmedDateField orders the results by confirmed_date field.
func ByConfirmedDateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConfirmedDateStep(), sql.OrderByField(field, opts...))
	}
}

// ByProposedDatesCount orders the results by proposed_dates count.
func ByProposedDatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProposedDatesStep(), opts...)
	}
}

// ByProposedDates orders the results by proposed_dates terms.
func ByProposedDates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProposedDatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newPrimaryCalendarStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrimaryCalendarInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PrimaryCalendarTable, PrimaryCalendarColumn),
	)
}
func newConfirmedDateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConfirmedDateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ConfirmedDateTable, ConfirmedDateColumn),
	)
}
func newProposedDatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProposedDatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProposedDatesTable, ProposedDatesColumn),
	)
}
