// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/koo-arch/adjusta-backend/ent/event"
	"github.com/koo-arch/adjusta-backend/ent/predicate"
	"github.com/koo-arch/adjusta-backend/ent/proposeddate"
)

// ProposedDateUpdate is the builder for updating ProposedDate entities.
type ProposedDateUpdate struct {
	config
	hooks    []Hook
	mutation *ProposedDateMutation
}

// Where appends a list predicates to the ProposedDateUpdate builder.
func (pdu *ProposedDateUpdate) Where(ps ...predicate.ProposedDate) *ProposedDateUpdate {
	pdu.mutation.Where(ps...)
	return pdu
}

// SetUpdatedAt sets the "updated_at" field.
func (pdu *ProposedDateUpdate) SetUpdatedAt(t time.Time) *ProposedDateUpdate {
	pdu.mutation.SetUpdatedAt(t)
	return pdu
}

// SetDeletedAt sets the "deleted_at" field.
func (pdu *ProposedDateUpdate) SetDeletedAt(t time.Time) *ProposedDateUpdate {
	pdu.mutation.SetDeletedAt(t)
	return pdu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pdu *ProposedDateUpdate) SetNillableDeletedAt(t *time.Time) *ProposedDateUpdate {
	if t != nil {
		pdu.SetDeletedAt(*t)
	}
	return pdu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (pdu *ProposedDateUpdate) ClearDeletedAt() *ProposedDateUpdate {
	pdu.mutation.ClearDeletedAt()
	return pdu
}

// SetEventID sets the "event_id" field.
func (pdu *ProposedDateUpdate) SetEventID(u uuid.UUID) *ProposedDateUpdate {
	pdu.mutation.SetEventID(u)
	return pdu
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (pdu *ProposedDateUpdate) SetNillableEventID(u *uuid.UUID) *ProposedDateUpdate {
	if u != nil {
		pdu.SetEventID(*u)
	}
	return pdu
}

// ClearEventID clears the value of the "event_id" field.
func (pdu *ProposedDateUpdate) ClearEventID() *ProposedDateUpdate {
	pdu.mutation.ClearEventID()
	return pdu
}

// SetGoogleEventID sets the "google_event_id" field.
func (pdu *ProposedDateUpdate) SetGoogleEventID(s string) *ProposedDateUpdate {
	pdu.mutation.SetGoogleEventID(s)
	return pdu
}

// SetNillableGoogleEventID sets the "google_event_id" field if the given value is not nil.
func (pdu *ProposedDateUpdate) SetNillableGoogleEventID(s *string) *ProposedDateUpdate {
	if s != nil {
		pdu.SetGoogleEventID(*s)
	}
	return pdu
}

// ClearGoogleEventID clears the value of the "google_event_id" field.
func (pdu *ProposedDateUpdate) ClearGoogleEventID() *ProposedDateUpdate {
	pdu.mutation.ClearGoogleEventID()
	return pdu
}

// SetStartTime sets the "start_time" field.
func (pdu *ProposedDateUpdate) SetStartTime(t time.Time) *ProposedDateUpdate {
	pdu.mutation.SetStartTime(t)
	return pdu
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (pdu *ProposedDateUpdate) SetNillableStartTime(t *time.Time) *ProposedDateUpdate {
	if t != nil {
		pdu.SetStartTime(*t)
	}
	return pdu
}

// SetEndTime sets the "end_time" field.
func (pdu *ProposedDateUpdate) SetEndTime(t time.Time) *ProposedDateUpdate {
	pdu.mutation.SetEndTime(t)
	return pdu
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (pdu *ProposedDateUpdate) SetNillableEndTime(t *time.Time) *ProposedDateUpdate {
	if t != nil {
		pdu.SetEndTime(*t)
	}
	return pdu
}

// SetPriority sets the "priority" field.
func (pdu *ProposedDateUpdate) SetPriority(i int) *ProposedDateUpdate {
	pdu.mutation.ResetPriority()
	pdu.mutation.SetPriority(i)
	return pdu
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (pdu *ProposedDateUpdate) SetNillablePriority(i *int) *ProposedDateUpdate {
	if i != nil {
		pdu.SetPriority(*i)
	}
	return pdu
}

// AddPriority adds i to the "priority" field.
func (pdu *ProposedDateUpdate) AddPriority(i int) *ProposedDateUpdate {
	pdu.mutation.AddPriority(i)
	return pdu
}

// SetStatus sets the "status" field.
func (pdu *ProposedDateUpdate) SetStatus(pr proposeddate.Status) *ProposedDateUpdate {
	pdu.mutation.SetStatus(pr)
	return pdu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pdu *ProposedDateUpdate) SetNillableStatus(pr *proposeddate.Status) *ProposedDateUpdate {
	if pr != nil {
		pdu.SetStatus(*pr)
	}
	return pdu
}

// SetSyncStatus sets the "sync_status" field.
func (pdu *ProposedDateUpdate) SetSyncStatus(ps proposeddate.SyncStatus) *ProposedDateUpdate {
	pdu.mutation.SetSyncStatus(ps)
	return pdu
}

// SetNillableSyncStatus sets the "sync_status" field if the given value is not nil.
func (pdu *ProposedDateUpdate) SetNillableSyncStatus(ps *proposeddate.SyncStatus) *ProposedDateUpdate {
	if ps != nil {
		pdu.SetSyncStatus(*ps)
	}
	return pdu
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (pdu *ProposedDateUpdate) SetLastSyncedAt(t time.Time) *ProposedDateUpdate {
	pdu.mutation.SetLastSyncedAt(t)
	return pdu
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (pdu *ProposedDateUpdate) SetNillableLastSyncedAt(t *time.Time) *ProposedDateUpdate {
	if t != nil {
		pdu.SetLastSyncedAt(*t)
	}
	return pdu
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (pdu *ProposedDateUpdate) ClearLastSyncedAt() *ProposedDateUpdate {
	pdu.mutation.ClearLastSyncedAt()
	return pdu
}

// SetLastSyncError sets the "last_sync_error" field.
func (pdu *ProposedDateUpdate) SetLastSyncError(s string) *ProposedDateUpdate {
	pdu.mutation.SetLastSyncError(s)
	return pdu
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (pdu *ProposedDateUpdate) SetNillableLastSyncError(s *string) *ProposedDateUpdate {
	if s != nil {
		pdu.SetLastSyncError(*s)
	}
	return pdu
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (pdu *ProposedDateUpdate) ClearLastSyncError() *ProposedDateUpdate {
	pdu.mutation.ClearLastSyncError()
	return pdu
}

// SetEvent sets the "event" edge to the Event entity.
func (pdu *ProposedDateUpdate) SetEvent(e *Event) *ProposedDateUpdate {
	return pdu.SetEventID(e.ID)
}

// Mutation returns the ProposedDateMutation object of the builder.
func (pdu *ProposedDateUpdate) Mutation() *ProposedDateMutation {
	return pdu.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (pdu *ProposedDateUpdate) ClearEvent() *ProposedDateUpdate {
	pdu.mutation.ClearEvent()
	return pdu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pdu *ProposedDateUpdate) Save(ctx context.Context) (int, error) {
	if err := pdu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, pdu.sqlSave, pdu.mutation, pdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pdu *ProposedDateUpdate) SaveX(ctx context.Context) int {
	affected, err := pdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pdu *ProposedDateUpdate) Exec(ctx context.Context) error {
	_, err := pdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pdu *ProposedDateUpdate) ExecX(ctx context.Context) {
	if err := pdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pdu *ProposedDateUpdate) defaults() error {
	if _, ok := pdu.mutation.UpdatedAt(); !ok {
		if proposeddate.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proposeddate.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proposeddate.UpdateDefaultUpdatedAt()
		pdu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (pdu *ProposedDateUpdate) check() error {
	if v, ok := pdu.mutation.Status(); ok {
		if err := proposeddate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProposedDate.status": %w`, err)}
		}
	}
	if v, ok := pdu.mutation.SyncStatus(); ok {
		if err := proposeddate.SyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "sync_status", err: fmt.Errorf(`ent: validator failed for field "ProposedDate.sync_status": %w`, err)}
		}
	}
	return nil
}

func (pdu *ProposedDateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(proposeddate.Table, proposeddate.Columns, sqlgraph.NewFieldSpec(proposeddate.FieldID, field.TypeUUID))
	if ps := pdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pdu.mutation.UpdatedAt(); ok {
		_spec.SetField(proposeddate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pdu.mutation.DeletedAt(); ok {
		_spec.SetField(proposeddate.FieldDeletedAt, field.TypeTime, value)
	}
	if pdu.mutation.DeletedAtCleared() {
		_spec.ClearField(proposeddate.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := pdu.mutation.GoogleEventID(); ok {
		_spec.SetField(proposeddate.FieldGoogleEventID, field.TypeString, value)
	}
	if pdu.mutation.GoogleEventIDCleared() {
		_spec.ClearField(proposeddate.FieldGoogleEventID, field.TypeString)
	}
	if value, ok := pdu.mutation.StartTime(); ok {
		_spec.SetField(proposeddate.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := pdu.mutation.EndTime(); ok {
		_spec.SetField(proposeddate.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := pdu.mutation.Priority(); ok {
		_spec.SetField(proposeddate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := pdu.mutation.AddedPriority(); ok {
		_spec.AddField(proposeddate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := pdu.mutation.Status(); ok {
		_spec.SetField(proposeddate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := pdu.mutation.SyncStatus(); ok {
		_spec.SetField(proposeddate.FieldSyncStatus, field.TypeEnum, value)
	}
	if value, ok := pdu.mutation.LastSyncedAt(); ok {
		_spec.SetField(proposeddate.FieldLastSyncedAt, field.TypeTime, value)
	}
	if pdu.mutation.LastSyncedAtCleared() {
		_spec.ClearField(proposeddate.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := pdu.mutation.LastSyncError(); ok {
		_spec.SetField(proposeddate.FieldLastSyncError, field.TypeString, value)
	}
	if pdu.mutation.LastSyncErrorCleared() {
		_spec.ClearField(proposeddate.FieldLastSyncError, field.TypeString)
	}
	if pdu.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proposeddate.EventTable,
			Columns: []string{proposeddate.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pdu.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proposeddate.EventTable,
			Columns: []string{proposeddate.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proposeddate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pdu.mutation.done = true
	return n, nil
}

// ProposedDateUpdateOne is the builder for updating a single ProposedDate entity.
type ProposedDateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProposedDateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (pduo *ProposedDateUpdateOne) SetUpdatedAt(t time.Time) *ProposedDateUpdateOne {
	pduo.mutation.SetUpdatedAt(t)
	return pduo
}

// SetDeletedAt sets the "deleted_at" field.
func (pduo *ProposedDateUpdateOne) SetDeletedAt(t time.Time) *ProposedDateUpdateOne {
	pduo.mutation.SetDeletedAt(t)
	return pduo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pduo *ProposedDateUpdateOne) SetNillableDeletedAt(t *time.Time) *ProposedDateUpdateOne {
	if t != nil {
		pduo.SetDeletedAt(*t)
	}
	return pduo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (pduo *ProposedDateUpdateOne) ClearDeletedAt() *ProposedDateUpdateOne {
	pduo.mutation.ClearDeletedAt()
	return pduo
}

// SetEventID sets the "event_id" field.
func (pduo *ProposedDateUpdateOne) SetEventID(u uuid.UUID) *ProposedDateUpdateOne {
	pduo.mutation.SetEventID(u)
	return pduo
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (pduo *ProposedDateUpdateOne) SetNillableEventID(u *uuid.UUID) *ProposedDateUpdateOne {
	if u != nil {
		pduo.SetEventID(*u)
	}
	return pduo
}

// ClearEventID clears the value of the "event_id" field.
func (pduo *ProposedDateUpdateOne) ClearEventID() *ProposedDateUpdateOne {
	pduo.mutation.ClearEventID()
	return pduo
}

// SetGoogleEventID sets the "google_event_id" field.
func (pduo *ProposedDateUpdateOne) SetGoogleEventID(s string) *ProposedDateUpdateOne {
	pduo.mutation.SetGoogleEventID(s)
	return pduo
}

// SetNillableGoogleEventID sets the "google_event_id" field if the given value is not nil.
func (pduo *ProposedDateUpdateOne) SetNillableGoogleEventID(s *string) *ProposedDateUpdateOne {
	if s != nil {
		pduo.SetGoogleEventID(*s)
	}
	return pduo
}

// ClearGoogleEventID clears the value of the "google_event_id" field.
func (pduo *ProposedDateUpdateOne) ClearGoogleEventID() *ProposedDateUpdateOne {
	pduo.mutation.ClearGoogleEventID()
	return pduo
}

// SetStartTime sets the "start_time" field.
func (pduo *ProposedDateUpdateOne) SetStartTime(t time.Time) *ProposedDateUpdateOne {
	pduo.mutation.SetStartTime(t)
	return pduo
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (pduo *ProposedDateUpdateOne) SetNillableStartTime(t *time.Time) *ProposedDateUpdateOne {
	if t != nil {
		pduo.SetStartTime(*t)
	}
	return pduo
}

// SetEndTime sets the "end_time" field.
func (pduo *ProposedDateUpdateOne) SetEndTime(t time.Time) *ProposedDateUpdateOne {
	pduo.mutation.SetEndTime(t)
	return pduo
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (pduo *ProposedDateUpdateOne) SetNillableEndTime(t *time.Time) *ProposedDateUpdateOne {
	if t != nil {
		pduo.SetEndTime(*t)
	}
	return pduo
}

// SetPriority sets the "priority" field.
func (pduo *ProposedDateUpdateOne) SetPriority(i int) *ProposedDateUpdateOne {
	pduo.mutation.ResetPriority()
	pduo.mutation.SetPriority(i)
	return pduo
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (pduo *ProposedDateUpdateOne) SetNillablePriority(i *int) *ProposedDateUpdateOne {
	if i != nil {
		pduo.SetPriority(*i)
	}
	return pduo
}

// AddPriority adds i to the "priority" field.
func (pduo *ProposedDateUpdateOne) AddPriority(i int) *ProposedDateUpdateOne {
	pduo.mutation.AddPriority(i)
	return pduo
}

// SetStatus sets the "status" field.
func (pduo *ProposedDateUpdateOne) SetStatus(pr proposeddate.Status) *ProposedDateUpdateOne {
	pduo.mutation.SetStatus(pr)
	return pduo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pduo *ProposedDateUpdateOne) SetNillableStatus(pr *proposeddate.Status) *ProposedDateUpdateOne {
	if pr != nil {
		pduo.SetStatus(*pr)
	}
	return pduo
}

// SetSyncStatus sets the "sync_status" field.
func (pduo *ProposedDateUpdateOne) SetSyncStatus(ps proposeddate.SyncStatus) *ProposedDateUpdateOne {
	pduo.mutation.SetSyncStatus(ps)
	return pduo
}

// SetNillableSyncStatus sets the "sync_status" field if the given value is not nil.
func (pduo *ProposedDateUpdateOne) SetNillableSyncStatus(ps *proposeddate.SyncStatus) *ProposedDateUpdateOne {
	if ps != nil {
		pduo.SetSyncStatus(*ps)
	}
	return pduo
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (pduo *ProposedDateUpdateOne) SetLastSyncedAt(t time.Time) *ProposedDateUpdateOne {
	pduo.mutation.SetLastSyncedAt(t)
	return pduo
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (pduo *ProposedDateUpdateOne) SetNillableLastSyncedAt(t *time.Time) *ProposedDateUpdateOne {
	if t != nil {
		pduo.SetLastSyncedAt(*t)
	}
	return pduo
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (pduo *ProposedDateUpdateOne) ClearLastSyncedAt() *ProposedDateUpdateOne {
	pduo.mutation.ClearLastSyncedAt()
	return pduo
}

// SetLastSyncError sets the "last_sync_error" field.
func (pduo *ProposedDateUpdateOne) SetLastSyncError(s string) *ProposedDateUpdateOne {
	pduo.mutation.SetLastSyncError(s)
	return pduo
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (pduo *ProposedDateUpdateOne) SetNillableLastSyncError(s *string) *ProposedDateUpdateOne {
	if s != nil {
		pduo.SetLastSyncError(*s)
	}
	return pduo
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (pduo *ProposedDateUpdateOne) ClearLastSyncError() *ProposedDateUpdateOne {
	pduo.mutation.ClearLastSyncError()
	return pduo
}

// SetEvent sets the "event" edge to the Event entity.
func (pduo *ProposedDateUpdateOne) SetEvent(e *Event) *ProposedDateUpdateOne {
	return pduo.SetEventID(e.ID)
}

// Mutation returns the ProposedDateMutation object of the builder.
func (pduo *ProposedDateUpdateOne) Mutation() *ProposedDateMutation {
	return pduo.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (pduo *ProposedDateUpdateOne) ClearEvent() *ProposedDateUpdateOne {
	pduo.mutation.ClearEvent()
	return pduo
}

// Where appends a list predicates to the ProposedDateUpdate builder.
func (pduo *ProposedDateUpdateOne) Where(ps ...predicate.ProposedDate) *ProposedDateUpdateOne {
	pduo.mutation.Where(ps...)
	return pduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pduo *ProposedDateUpdateOne) Select(field string, fields ...string) *ProposedDateUpdateOne {
	pduo.fields = append([]string{field}, fields...)
	return pduo
}

// Save executes the query and returns the updated ProposedDate entity.
func (pduo *ProposedDateUpdateOne) Save(ctx context.Context) (*ProposedDate, error) {
	if err := pduo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, pduo.sqlSave, pduo.mutation, pduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pduo *ProposedDateUpdateOne) SaveX(ctx context.Context) *ProposedDate {
	node, err := pduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pduo *ProposedDateUpdateOne) Exec(ctx context.Context) error {
	_, err := pduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pduo *ProposedDateUpdateOne) ExecX(ctx context.Context) {
	if err := pduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pduo *ProposedDateUpdateOne) defaults() error {
	if _, ok := pduo.mutation.UpdatedAt(); !ok {
		if proposeddate.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proposeddate.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proposeddate.UpdateDefaultUpdatedAt()
		pduo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (pduo *ProposedDateUpdateOne) check() error {
	if v, ok := pduo.mutation.Status(); ok {
		if err := proposeddate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProposedDate.status": %w`, err)}
		}
	}
	if v, ok := pduo.mutation.SyncStatus(); ok {
		if err := proposeddate.SyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "sync_status", err: fmt.Errorf(`ent: validator failed for field "ProposedDate.sync_status": %w`, err)}
		}
	}
	return nil
}

func (pduo *ProposedDateUpdateOne) sqlSave(ctx context.Context) (_node *ProposedDate, err error) {
	if err := pduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proposeddate.Table, proposeddate.Columns, sqlgraph.NewFieldSpec(proposeddate.FieldID, field.TypeUUID))
	id, ok := pduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProposedDate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proposeddate.FieldID)
		for _, f := range fields {
			if !proposeddate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proposeddate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pduo.mutation.UpdatedAt(); ok {
		_spec.SetField(proposeddate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pduo.mutation.DeletedAt(); ok {
		_spec.SetField(proposeddate.FieldDeletedAt, field.TypeTime, value)
	}
	if pduo.mutation.DeletedAtCleared() {
		_spec.ClearField(proposeddate.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := pduo.mutation.GoogleEventID(); ok {
		_spec.SetField(proposeddate.FieldGoogleEventID, field.TypeString, value)
	}
	if pduo.mutation.GoogleEventIDCleared() {
		_spec.ClearField(proposeddate.FieldGoogleEventID, field.TypeString)
	}
	if value, ok := pduo.mutation.StartTime(); ok {
		_spec.SetField(proposeddate.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := pduo.mutation.EndTime(); ok {
		_spec.SetField(proposeddate.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := pduo.mutation.Priority(); ok {
		_spec.SetField(proposeddate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := pduo.mutation.AddedPriority(); ok {
		_spec.AddField(proposeddate.FieldPriority, field.TypeInt, value)
	}
	if value, ok := pduo.mutation.Status(); ok {
		_spec.SetField(proposeddate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := pduo.mutation.SyncStatus(); ok {
		_spec.SetField(proposeddate.FieldSyncStatus, field.TypeEnum, value)
	}
	if value, ok := pduo.mutation.LastSyncedAt(); ok {
		_spec.SetField(proposeddate.FieldLastSyncedAt, field.TypeTime, value)
	}
	if pduo.mutation.LastSyncedAtCleared() {
		_spec.ClearField(proposeddate.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := pduo.mutation.LastSyncError(); ok {
		_spec.SetField(proposeddate.FieldLastSyncError, field.TypeString, value)
	}
	if pduo.mutation.LastSyncErrorCleared() {
		_spec.ClearField(proposeddate.FieldLastSyncError, field.TypeString)
	}
	if pduo.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proposeddate.EventTable,
			Columns: []string{proposeddate.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pduo.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   proposeddate.EventTable,
			Columns: []string{proposeddate.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProposedDate{config: pduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proposeddate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pduo.mutation.done = true
	return _node, nil
}
