// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/koo-arch/adjusta-backend/ent/calendar"
	"github.com/koo-arch/adjusta-backend/ent/predicate"
	"github.com/koo-arch/adjusta-backend/ent/user"
	"github.com/koo-arch/adjusta-backend/ent/usercalendar"
)

// UserCalendarQuery is the builder for querying UserCalendar entities.
type UserCalendarQuery struct {
	config
	ctx          *QueryContext
	order        []usercalendar.OrderOption
	inters       []Interceptor
	predicates   []predicate.UserCalendar
	withUser     *UserQuery
	withCalendar *CalendarQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserCalendarQuery builder.
func (ucq *UserCalendarQuery) Where(ps ...predicate.UserCalendar) *UserCalendarQuery {
	ucq.predicates = append(ucq.predicates, ps...)
	return ucq
}

// Limit the number of records to be returned by this query.
func (ucq *UserCalendarQuery) Limit(limit int) *UserCalendarQuery {
	ucq.ctx.Limit = &limit
	return ucq
}

// Offset to start from.
func (ucq *UserCalendarQuery) Offset(offset int) *UserCalendarQuery {
	ucq.ctx.Offset = &offset
	return ucq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ucq *UserCalendarQuery) Unique(unique bool) *UserCalendarQuery {
	ucq.ctx.Unique = &unique
	return ucq
}

// Order specifies how the records should be ordered.
func (ucq *UserCalendarQuery) Order(o ...usercalendar.OrderOption) *UserCalendarQuery {
	ucq.order = append(ucq.order, o...)
	return ucq
}

// QueryUser chains the current query on the "user" edge.
func (ucq *UserCalendarQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ucq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ucq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ucq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usercalendar.Table, usercalendar.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usercalendar.UserTable, usercalendar.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ucq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCalendar chains the current query on the "calendar" edge.
func (ucq *UserCalendarQuery) QueryCalendar() *CalendarQuery {
	query := (&CalendarClient{config: ucq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ucq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ucq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usercalendar.Table, usercalendar.FieldID, selector),
			sqlgraph.To(calendar.Table, calendar.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usercalendar.CalendarTable, usercalendar.CalendarColumn),
		)
		fromU = sqlgraph.SetNeighbors(ucq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserCalendar entity from the query.
// Returns a *NotFoundError when no UserCalendar was found.
func (ucq *UserCalendarQuery) First(ctx context.Context) (*UserCalendar, error) {
	nodes, err := ucq.Limit(1).All(setContextOp(ctx, ucq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usercalendar.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ucq *UserCalendarQuery) FirstX(ctx context.Context) *UserCalendar {
	node, err := ucq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserCalendar ID from the query.
// Returns a *NotFoundError when no UserCalendar ID was found.
func (ucq *UserCalendarQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ucq.Limit(1).IDs(setContextOp(ctx, ucq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usercalendar.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ucq *UserCalendarQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ucq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserCalendar entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserCalendar entity is found.
// Returns a *NotFoundError when no UserCalendar entities are found.
func (ucq *UserCalendarQuery) Only(ctx context.Context) (*UserCalendar, error) {
	nodes, err := ucq.Limit(2).All(setContextOp(ctx, ucq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usercalendar.Label}
	default:
		return nil, &NotSingularError{usercalendar.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ucq *UserCalendarQuery) OnlyX(ctx context.Context) *UserCalendar {
	node, err := ucq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserCalendar ID in the query.
// Returns a *NotSingularError when more than one UserCalendar ID is found.
// Returns a *NotFoundError when no entities are found.
func (ucq *UserCalendarQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ucq.Limit(2).IDs(setContextOp(ctx, ucq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usercalendar.Label}
	default:
		err = &NotSingularError{usercalendar.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ucq *UserCalendarQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ucq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserCalendars.
func (ucq *UserCalendarQuery) All(ctx context.Context) ([]*UserCalendar, error) {
	ctx = setContextOp(ctx, ucq.ctx, ent.OpQueryAll)
	if err := ucq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserCalendar, *UserCalendarQuery]()
	return withInterceptors[[]*UserCalendar](ctx, ucq, qr, ucq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ucq *UserCalendarQuery) AllX(ctx context.Context) []*UserCalendar {
	nodes, err := ucq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserCalendar IDs.
func (ucq *UserCalendarQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if ucq.ctx.Unique == nil && ucq.path != nil {
		ucq.Unique(true)
	}
	ctx = setContextOp(ctx, ucq.ctx, ent.OpQueryIDs)
	if err = ucq.Select(usercalendar.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ucq *UserCalendarQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ucq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ucq *UserCalendarQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ucq.ctx, ent.OpQueryCount)
	if err := ucq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ucq, querierCount[*UserCalendarQuery](), ucq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ucq *UserCalendarQuery) CountX(ctx context.Context) int {
	count, err := ucq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ucq *UserCalendarQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ucq.ctx, ent.OpQueryExist)
	switch _, err := ucq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ucq *UserCalendarQuery) ExistX(ctx context.Context) bool {
	exist, err := ucq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserCalendarQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ucq *UserCalendarQuery) Clone() *UserCalendarQuery {
	if ucq == nil {
		return nil
	}
	return &UserCalendarQuery{
		config:       ucq.config,
		ctx:          ucq.ctx.Clone(),
		order:        append([]usercalendar.OrderOption{}, ucq.order...),
		inters:       append([]Interceptor{}, ucq.inters...),
		predicates:   append([]predicate.UserCalendar{}, ucq.predicates...),
		withUser:     ucq.withUser.Clone(),
		withCalendar: ucq.withCalendar.Clone(),
		// clone intermediate query.
		sql:  ucq.sql.Clone(),
		path: ucq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ucq *UserCalendarQuery) WithUser(opts ...func(*UserQuery)) *UserCalendarQuery {
	query := (&UserClient{config: ucq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ucq.withUser = query
	return ucq
}

// WithCalendar tells the query-builder to eager-load the nodes that are connected to
// the "calendar" edge. The optional arguments are used to configure the query builder of the edge.
func (ucq *UserCalendarQuery) WithCalendar(opts ...func(*CalendarQuery)) *UserCalendarQuery {
	query := (&CalendarClient{config: ucq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ucq.withCalendar = query
	return ucq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserCalendar.Query().
//		GroupBy(usercalendar.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ucq *UserCalendarQuery) GroupBy(field string, fields ...string) *UserCalendarGroupBy {
	ucq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserCalendarGroupBy{build: ucq}
	grbuild.flds = &ucq.ctx.Fields
	grbuild.label = usercalendar.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.UserCalendar.Query().
//		Select(usercalendar.FieldCreatedAt).
//		Scan(ctx, &v)
func (ucq *UserCalendarQuery) Select(fields ...string) *UserCalendarSelect {
	ucq.ctx.Fields = append(ucq.ctx.Fields, fields...)
	sbuild := &UserCalendarSelect{UserCalendarQuery: ucq}
	sbuild.label = usercalendar.Label
	sbuild.flds, sbuild.scan = &ucq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserCalendarSelect configured with the given aggregations.
func (ucq *UserCalendarQuery) Aggregate(fns ...AggregateFunc) *UserCalendarSelect {
	return ucq.Select().Aggregate(fns...)
}

func (ucq *UserCalendarQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ucq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ucq); err != nil {
				return err
			}
		}
	}
	for _, f := range ucq.ctx.Fields {
		if !usercalendar.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ucq.path != nil {
		prev, err := ucq.path(ctx)
		if err != nil {
			return err
		}
		ucq.sql = prev
	}
	return nil
}

func (ucq *UserCalendarQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserCalendar, error) {
	var (
		nodes       = []*UserCalendar{}
		_spec       = ucq.querySpec()
		loadedTypes = [2]bool{
			ucq.withUser != nil,
			ucq.withCalendar != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserCalendar).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserCalendar{config: ucq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ucq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ucq.withUser; query != nil {
		if err := ucq.loadUser(ctx, query, nodes, nil,
			func(n *UserCalendar, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := ucq.withCalendar; query != nil {
		if err := ucq.loadCalendar(ctx, query, nodes, nil,
			func(n *UserCalendar, e *Calendar) { n.Edges.Calendar = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ucq *UserCalendarQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserCalendar, init func(*UserCalendar), assign func(*UserCalendar, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*UserCalendar)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ucq *UserCalendarQuery) loadCalendar(ctx context.Context, query *CalendarQuery, nodes []*UserCalendar, init func(*UserCalendar), assign func(*UserCalendar, *Calendar)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*UserCalendar)
	for i := range nodes {
		fk := nodes[i].CalendarID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(calendar.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "calendar_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ucq *UserCalendarQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ucq.querySpec()
	_spec.Node.Columns = ucq.ctx.Fields
	if len(ucq.ctx.Fields) > 0 {
		_spec.Unique = ucq.ctx.Unique != nil && *ucq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ucq.driver, _spec)
}

func (ucq *UserCalendarQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usercalendar.Table, usercalendar.Columns, sqlgraph.NewFieldSpec(usercalendar.FieldID, field.TypeUUID))
	_spec.From = ucq.sql
	if unique := ucq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ucq.path != nil {
		_spec.Unique = true
	}
	if fields := ucq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usercalendar.FieldID)
		for i := range fields {
			if fields[i] != usercalendar.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ucq.withUser != nil {
			_spec.Node.AddColumnOnce(usercalendar.FieldUserID)
		}
		if ucq.withCalendar != nil {
			_spec.Node.AddColumnOnce(usercalendar.FieldCalendarID)
		}
	}
	if ps := ucq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ucq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ucq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ucq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ucq *UserCalendarQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ucq.driver.Dialect())
	t1 := builder.Table(usercalendar.Table)
	columns := ucq.ctx.Fields
	if len(columns) == 0 {
		columns = usercalendar.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ucq.sql != nil {
		selector = ucq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ucq.ctx.Unique != nil && *ucq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ucq.predicates {
		p(selector)
	}
	for _, p := range ucq.order {
		p(selector)
	}
	if offset := ucq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ucq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserCalendarGroupBy is the group-by builder for UserCalendar entities.
type UserCalendarGroupBy struct {
	selector
	build *UserCalendarQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ucgb *UserCalendarGroupBy) Aggregate(fns ...AggregateFunc) *UserCalendarGroupBy {
	ucgb.fns = append(ucgb.fns, fns...)
	return ucgb
}

// Scan applies the selector query and scans the result into the given value.
func (ucgb *UserCalendarGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ucgb.build.ctx, ent.OpQueryGroupBy)
	if err := ucgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserCalendarQuery, *UserCalendarGroupBy](ctx, ucgb.build, ucgb, ucgb.build.inters, v)
}

func (ucgb *UserCalendarGroupBy) sqlScan(ctx context.Context, root *UserCalendarQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ucgb.fns))
	for _, fn := range ucgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ucgb.flds)+len(ucgb.fns))
		for _, f := range *ucgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ucgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ucgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserCalendarSelect is the builder for selecting fields of UserCalendar entities.
type UserCalendarSelect struct {
	*UserCalendarQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ucs *UserCalendarSelect) Aggregate(fns ...AggregateFunc) *UserCalendarSelect {
	ucs.fns = append(ucs.fns, fns...)
	return ucs
}

// Scan applies the selector query and scans the result into the given value.
func (ucs *UserCalendarSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ucs.ctx, ent.OpQuerySelect)
	if err := ucs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserCalendarQuery, *UserCalendarSelect](ctx, ucs.UserCalendarQuery, ucs, ucs.inters, v)
}

func (ucs *UserCalendarSelect) sqlScan(ctx context.Context, root *UserCalendarQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ucs.fns))
	for _, fn := range ucs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ucs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ucs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
