// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/koo-arch/adjusta-backend/ent/calendar"
	"github.com/koo-arch/adjusta-backend/ent/predicate"
	"github.com/koo-arch/adjusta-backend/ent/user"
	"github.com/koo-arch/adjusta-backend/ent/usercalendar"
)

// UserCalendarUpdate is the builder for updating UserCalendar entities.
type UserCalendarUpdate struct {
	config
	hooks    []Hook
	mutation *UserCalendarMutation
}

// Where appends a list predicates to the UserCalendarUpdate builder.
func (ucu *UserCalendarUpdate) Where(ps ...predicate.UserCalendar) *UserCalendarUpdate {
	ucu.mutation.Where(ps...)
	return ucu
}

// SetUpdatedAt sets the "updated_at" field.
func (ucu *UserCalendarUpdate) SetUpdatedAt(t time.Time) *UserCalendarUpdate {
	ucu.mutation.SetUpdatedAt(t)
	return ucu
}

// SetDeletedAt sets the "deleted_at" field.
func (ucu *UserCalendarUpdate) SetDeletedAt(t time.Time) *UserCalendarUpdate {
	ucu.mutation.SetDeletedAt(t)
	return ucu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ucu *UserCalendarUpdate) SetNillableDeletedAt(t *time.Time) *UserCalendarUpdate {
	if t != nil {
		ucu.SetDeletedAt(*t)
	}
	return ucu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ucu *UserCalendarUpdate) ClearDeletedAt() *UserCalendarUpdate {
	ucu.mutation.ClearDeletedAt()
	return ucu
}

// SetUserID sets the "user_id" field.
func (ucu *UserCalendarUpdate) SetUserID(u uuid.UUID) *UserCalendarUpdate {
	ucu.mutation.SetUserID(u)
	return ucu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ucu *UserCalendarUpdate) SetNillableUserID(u *uuid.UUID) *UserCalendarUpdate {
	if u != nil {
		ucu.SetUserID(*u)
	}
	return ucu
}

// SetCalendarID sets the "calendar_id" field.
func (ucu *UserCalendarUpdate) SetCalendarID(u uuid.UUID) *UserCalendarUpdate {
	ucu.mutation.SetCalendarID(u)
	return ucu
}

// SetNillableCalendarID sets the "calendar_id" field if the given value is not nil.
func (ucu *UserCalendarUpdate) SetNillableCalendarID(u *uuid.UUID) *UserCalendarUpdate {
	if u != nil {
		ucu.SetCalendarID(*u)
	}
	return ucu
}

// SetRole sets the "role" field.
func (ucu *UserCalendarUpdate) SetRole(u usercalendar.Role) *UserCalendarUpdate {
	ucu.mutation.SetRole(u)
	return ucu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (ucu *UserCalendarUpdate) SetNillableRole(u *usercalendar.Role) *UserCalendarUpdate {
	if u != nil {
		ucu.SetRole(*u)
	}
	return ucu
}

// SetIsVisible sets the "is_visible" field.
func (ucu *UserCalendarUpdate) SetIsVisible(b bool) *UserCalendarUpdate {
	ucu.mutation.SetIsVisible(b)
	return ucu
}

// SetNillableIsVisible sets the "is_visible" field if the given value is not nil.
func (ucu *UserCalendarUpdate) SetNillableIsVisible(b *bool) *UserCalendarUpdate {
	if b != nil {
		ucu.SetIsVisible(*b)
	}
	return ucu
}

// SetSyncProposedDates sets the "sync_proposed_dates" field.
func (ucu *UserCalendarUpdate) SetSyncProposedDates(b bool) *UserCalendarUpdate {
	ucu.mutation.SetSyncProposedDates(b)
	return ucu
}

// SetNillableSyncProposedDates sets the "sync_proposed_dates" field if the given value is not nil.
func (ucu *UserCalendarUpdate) SetNillableSyncProposedDates(b *bool) *UserCalendarUpdate {
	if b != nil {
		ucu.SetSyncProposedDates(*b)
	}
	return ucu
}

// SetUser sets the "user" edge to the User entity.
func (ucu *UserCalendarUpdate) SetUser(u *User) *UserCalendarUpdate {
	return ucu.SetUserID(u.ID)
}

// SetCalendar sets the "calendar" edge to the Calendar entity.
func (ucu *UserCalendarUpdate) SetCalendar(c *Calendar) *UserCalendarUpdate {
	return ucu.SetCalendarID(c.ID)
}

// Mutation returns the UserCalendarMutation object of the builder.
func (ucu *UserCalendarUpdate) Mutation() *UserCalendarMutation {
	return ucu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ucu *UserCalendarUpdate) ClearUser() *UserCalendarUpdate {
	ucu.mutation.ClearUser()
	return ucu
}

// ClearCalendar clears the "calendar" edge to the Calendar entity.
func (ucu *UserCalendarUpdate) ClearCalendar() *UserCalendarUpdate {
	ucu.mutation.ClearCalendar()
	return ucu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ucu *UserCalendarUpdate) Save(ctx context.Context) (int, error) {
	ucu.defaults()
	return withHooks(ctx, ucu.sqlSave, ucu.mutation, ucu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ucu *UserCalendarUpdate) SaveX(ctx context.Context) int {
	affected, err := ucu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ucu *UserCalendarUpdate) Exec(ctx context.Context) error {
	_, err := ucu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucu *UserCalendarUpdate) ExecX(ctx context.Context) {
	if err := ucu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ucu *UserCalendarUpdate) defaults() {
	if _, ok := ucu.mutation.UpdatedAt(); !ok {
		v := usercalendar.UpdateDefaultUpdatedAt()
		ucu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ucu *UserCalendarUpdate) check() error {
	if v, ok := ucu.mutation.Role(); ok {
		if err := usercalendar.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "UserCalendar.role": %w`, err)}
		}
	}
	if ucu.mutation.UserCleared() && len(ucu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserCalendar.user"`)
	}
	if ucu.mutation.CalendarCleared() && len(ucu.mutation.CalendarIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserCalendar.calendar"`)
	}
	return nil
}

func (ucu *UserCalendarUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ucu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usercalendar.Table, usercalendar.Columns, sqlgraph.NewFieldSpec(usercalendar.FieldID, field.TypeUUID))
	if ps := ucu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ucu.mutation.UpdatedAt(); ok {
		_spec.SetField(usercalendar.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ucu.mutation.DeletedAt(); ok {
		_spec.SetField(usercalendar.FieldDeletedAt, field.TypeTime, value)
	}
	if ucu.mutation.DeletedAtCleared() {
		_spec.ClearField(usercalendar.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ucu.mutation.Role(); ok {
		_spec.SetField(usercalendar.FieldRole, field.TypeEnum, value)
	}
	if value, ok := ucu.mutation.IsVisible(); ok {
		_spec.SetField(usercalendar.FieldIsVisible, field.TypeBool, value)
	}
	if value, ok := ucu.mutation.SyncProposedDates(); ok {
		_spec.SetField(usercalendar.FieldSyncProposedDates, field.TypeBool, value)
	}
	if ucu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercalendar.UserTable,
			Columns: []string{usercalendar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ucu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercalendar.UserTable,
			Columns: []string{usercalendar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ucu.mutation.CalendarCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercalendar.CalendarTable,
			Columns: []string{usercalendar.CalendarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendar.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ucu.mutation.CalendarIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercalendar.CalendarTable,
			Columns: []string{usercalendar.CalendarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendar.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ucu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usercalendar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ucu.mutation.done = true
	return n, nil
}

// UserCalendarUpdateOne is the builder for updating a single UserCalendar entity.
type UserCalendarUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserCalendarMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ucuo *UserCalendarUpdateOne) SetUpdatedAt(t time.Time) *UserCalendarUpdateOne {
	ucuo.mutation.SetUpdatedAt(t)
	return ucuo
}

// SetDeletedAt sets the "deleted_at" field.
func (ucuo *UserCalendarUpdateOne) SetDeletedAt(t time.Time) *UserCalendarUpdateOne {
	ucuo.mutation.SetDeletedAt(t)
	return ucuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ucuo *UserCalendarUpdateOne) SetNillableDeletedAt(t *time.Time) *UserCalendarUpdateOne {
	if t != nil {
		ucuo.SetDeletedAt(*t)
	}
	return ucuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ucuo *UserCalendarUpdateOne) ClearDeletedAt() *UserCalendarUpdateOne {
	ucuo.mutation.ClearDeletedAt()
	return ucuo
}

// SetUserID sets the "user_id" field.
func (ucuo *UserCalendarUpdateOne) SetUserID(u uuid.UUID) *UserCalendarUpdateOne {
	ucuo.mutation.SetUserID(u)
	return ucuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ucuo *UserCalendarUpdateOne) SetNillableUserID(u *uuid.UUID) *UserCalendarUpdateOne {
	if u != nil {
		ucuo.SetUserID(*u)
	}
	return ucuo
}

// SetCalendarID sets the "calendar_id" field.
func (ucuo *UserCalendarUpdateOne) SetCalendarID(u uuid.UUID) *UserCalendarUpdateOne {
	ucuo.mutation.SetCalendarID(u)
	return ucuo
}

// SetNillableCalendarID sets the "calendar_id" field if the given value is not nil.
func (ucuo *UserCalendarUpdateOne) SetNillableCalendarID(u *uuid.UUID) *UserCalendarUpdateOne {
	if u != nil {
		ucuo.SetCalendarID(*u)
	}
	return ucuo
}

// SetRole sets the "role" field.
func (ucuo *UserCalendarUpdateOne) SetRole(u usercalendar.Role) *UserCalendarUpdateOne {
	ucuo.mutation.SetRole(u)
	return ucuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (ucuo *UserCalendarUpdateOne) SetNillableRole(u *usercalendar.Role) *UserCalendarUpdateOne {
	if u != nil {
		ucuo.SetRole(*u)
	}
	return ucuo
}

// SetIsVisible sets the "is_visible" field.
func (ucuo *UserCalendarUpdateOne) SetIsVisible(b bool) *UserCalendarUpdateOne {
	ucuo.mutation.SetIsVisible(b)
	return ucuo
}

// SetNillableIsVisible sets the "is_visible" field if the given value is not nil.
func (ucuo *UserCalendarUpdateOne) SetNillableIsVisible(b *bool) *UserCalendarUpdateOne {
	if b != nil {
		ucuo.SetIsVisible(*b)
	}
	return ucuo
}

// SetSyncProposedDates sets the "sync_proposed_dates" field.
func (ucuo *UserCalendarUpdateOne) SetSyncProposedDates(b bool) *UserCalendarUpdateOne {
	ucuo.mutation.SetSyncProposedDates(b)
	return ucuo
}

// SetNillableSyncProposedDates sets the "sync_proposed_dates" field if the given value is not nil.
func (ucuo *UserCalendarUpdateOne) SetNillableSyncProposedDates(b *bool) *UserCalendarUpdateOne {
	if b != nil {
		ucuo.SetSyncProposedDates(*b)
	}
	return ucuo
}

// SetUser sets the "user" edge to the User entity.
func (ucuo *UserCalendarUpdateOne) SetUser(u *User) *UserCalendarUpdateOne {
	return ucuo.SetUserID(u.ID)
}

// SetCalendar sets the "calendar" edge to the Calendar entity.
func (ucuo *UserCalendarUpdateOne) SetCalendar(c *Calendar) *UserCalendarUpdateOne {
	return ucuo.SetCalendarID(c.ID)
}

// Mutation returns the UserCalendarMutation object of the builder.
func (ucuo *UserCalendarUpdateOne) Mutation() *UserCalendarMutation {
	return ucuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ucuo *UserCalendarUpdateOne) ClearUser() *UserCalendarUpdateOne {
	ucuo.mutation.ClearUser()
	return ucuo
}

// ClearCalendar clears the "calendar" edge to the Calendar entity.
func (ucuo *UserCalendarUpdateOne) ClearCalendar() *UserCalendarUpdateOne {
	ucuo.mutation.ClearCalendar()
	return ucuo
}

// Where appends a list predicates to the UserCalendarUpdate builder.
func (ucuo *UserCalendarUpdateOne) Where(ps ...predicate.UserCalendar) *UserCalendarUpdateOne {
	ucuo.mutation.Where(ps...)
	return ucuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ucuo *UserCalendarUpdateOne) Select(field string, fields ...string) *UserCalendarUpdateOne {
	ucuo.fields = append([]string{field}, fields...)
	return ucuo
}

// Save executes the query and returns the updated UserCalendar entity.
func (ucuo *UserCalendarUpdateOne) Save(ctx context.Context) (*UserCalendar, error) {
	ucuo.defaults()
	return withHooks(ctx, ucuo.sqlSave, ucuo.mutation, ucuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ucuo *UserCalendarUpdateOne) SaveX(ctx context.Context) *UserCalendar {
	node, err := ucuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ucuo *UserCalendarUpdateOne) Exec(ctx context.Context) error {
	_, err := ucuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucuo *UserCalendarUpdateOne) ExecX(ctx context.Context) {
	if err := ucuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ucuo *UserCalendarUpdateOne) defaults() {
	if _, ok := ucuo.mutation.UpdatedAt(); !ok {
		v := usercalendar.UpdateDefaultUpdatedAt()
		ucuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ucuo *UserCalendarUpdateOne) check() error {
	if v, ok := ucuo.mutation.Role(); ok {
		if err := usercalendar.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "UserCalendar.role": %w`, err)}
		}
	}
	if ucuo.mutation.UserCleared() && len(ucuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserCalendar.user"`)
	}
	if ucuo.mutation.CalendarCleared() && len(ucuo.mutation.CalendarIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserCalendar.calendar"`)
	}
	return nil
}

func (ucuo *UserCalendarUpdateOne) sqlSave(ctx context.Context) (_node *UserCalendar, err error) {
	if err := ucuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usercalendar.Table, usercalendar.Columns, sqlgraph.NewFieldSpec(usercalendar.FieldID, field.TypeUUID))
	id, ok := ucuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserCalendar.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ucuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usercalendar.FieldID)
		for _, f := range fields {
			if !usercalendar.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usercalendar.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ucuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ucuo.mutation.UpdatedAt(); ok {
		_spec.SetField(usercalendar.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ucuo.mutation.DeletedAt(); ok {
		_spec.SetField(usercalendar.FieldDeletedAt, field.TypeTime, value)
	}
	if ucuo.mutation.DeletedAtCleared() {
		_spec.ClearField(usercalendar.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ucuo.mutation.Role(); ok {
		_spec.SetField(usercalendar.FieldRole, field.TypeEnum, value)
	}
	if value, ok := ucuo.mutation.IsVisible(); ok {
		_spec.SetField(usercalendar.FieldIsVisible, field.TypeBool, value)
	}
	if value, ok := ucuo.mutation.SyncProposedDates(); ok {
		_spec.SetField(usercalendar.FieldSyncProposedDates, field.TypeBool, value)
	}
	if ucuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercalendar.UserTable,
			Columns: []string{usercalendar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ucuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercalendar.UserTable,
			Columns: []string{usercalendar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ucuo.mutation.CalendarCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercalendar.CalendarTable,
			Columns: []string{usercalendar.CalendarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendar.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ucuo.mutation.CalendarIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usercalendar.CalendarTable,
			Columns: []string{usercalendar.CalendarColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendar.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserCalendar{config: ucuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ucuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usercalendar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ucuo.mutation.done = true
	return _node, nil
}
