// Code generated by ent, DO NOT EDIT.

package proposeddate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/koo-arch/adjusta-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldDeletedAt, v))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldEventID, v))
}

// GoogleEventID applies equality check predicate on the "google_event_id" field. It's identical to GoogleEventIDEQ.
func GoogleEventID(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldGoogleEventID, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldEndTime, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldPriority, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncError applies equality check predicate on the "last_sync_error" field. It's identical to LastSyncErrorEQ.
func LastSyncError(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldLastSyncError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotNull(FieldDeletedAt))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...uuid.UUID) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldEventID, vs...))
}

// GoogleEventIDEQ applies the EQ predicate on the "google_event_id" field.
func GoogleEventIDEQ(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldGoogleEventID, v))
}

// GoogleEventIDNEQ applies the NEQ predicate on the "google_event_id" field.
func GoogleEventIDNEQ(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldGoogleEventID, v))
}

// GoogleEventIDIn applies the In predicate on the "google_event_id" field.
func GoogleEventIDIn(vs ...string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldGoogleEventID, vs...))
}

// GoogleEventIDNotIn applies the NotIn predicate on the "google_event_id" field.
func GoogleEventIDNotIn(vs ...string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldGoogleEventID, vs...))
}

// GoogleEventIDGT applies the GT predicate on the "google_event_id" field.
func GoogleEventIDGT(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGT(FieldGoogleEventID, v))
}

// GoogleEventIDGTE applies the GTE predicate on the "google_event_id" field.
func GoogleEventIDGTE(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGTE(FieldGoogleEventID, v))
}

// GoogleEventIDLT applies the LT predicate on the "google_event_id" field.
func GoogleEventIDLT(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLT(FieldGoogleEventID, v))
}

// GoogleEventIDLTE applies the LTE predicate on the "google_event_id" field.
func GoogleEventIDLTE(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLTE(FieldGoogleEventID, v))
}

// GoogleEventIDContains applies the Contains predicate on the "google_event_id" field.
func GoogleEventIDContains(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldContains(FieldGoogleEventID, v))
}

// GoogleEventIDHasPrefix applies the HasPrefix predicate on the "google_event_id" field.
func GoogleEventIDHasPrefix(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldHasPrefix(FieldGoogleEventID, v))
}

// GoogleEventIDHasSuffix applies the HasSuffix predicate on the "google_event_id" field.
func GoogleEventIDHasSuffix(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldHasSuffix(FieldGoogleEventID, v))
}

// GoogleEventIDIsNil applies the IsNil predicate on the "google_event_id" field.
func GoogleEventIDIsNil() predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIsNull(FieldGoogleEventID))
}

// GoogleEventIDNotNil applies the NotNil predicate on the "google_event_id" field.
func GoogleEventIDNotNil() predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotNull(FieldGoogleEventID))
}

// GoogleEventIDEqualFold applies the EqualFold predicate on the "google_event_id" field.
func GoogleEventIDEqualFold(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEqualFold(FieldGoogleEventID, v))
}

// GoogleEventIDContainsFold applies the ContainsFold predicate on the "google_event_id" field.
func GoogleEventIDContainsFold(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldContainsFold(FieldGoogleEventID, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLTE(FieldStartTime, v))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLTE(FieldEndTime, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLTE(FieldPriority, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldStatus, vs...))
}

// SyncStatusEQ applies the EQ predicate on the "sync_status" field.
func SyncStatusEQ(v SyncStatus) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldSyncStatus, v))
}

// SyncStatusNEQ applies the NEQ predicate on the "sync_status" field.
func SyncStatusNEQ(v SyncStatus) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldSyncStatus, v))
}

// SyncStatusIn applies the In predicate on the "sync_status" field.
func SyncStatusIn(vs ...SyncStatus) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldSyncStatus, vs...))
}

// SyncStatusNotIn applies the NotIn predicate on the "sync_status" field.
func SyncStatusNotIn(vs ...SyncStatus) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldSyncStatus, vs...))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotNull(FieldLastSyncedAt))
}

// LastSyncErrorEQ applies the EQ predicate on the "last_sync_error" field.
func LastSyncErrorEQ(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEQ(FieldLastSyncError, v))
}

// LastSyncErrorNEQ applies the NEQ predicate on the "last_sync_error" field.
func LastSyncErrorNEQ(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNEQ(FieldLastSyncError, v))
}

// LastSyncErrorIn applies the In predicate on the "last_sync_error" field.
func LastSyncErrorIn(vs ...string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIn(FieldLastSyncError, vs...))
}

// LastSyncErrorNotIn applies the NotIn predicate on the "last_sync_error" field.
func LastSyncErrorNotIn(vs ...string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotIn(FieldLastSyncError, vs...))
}

// LastSyncErrorGT applies the GT predicate on the "last_sync_error" field.
func LastSyncErrorGT(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGT(FieldLastSyncError, v))
}

// LastSyncErrorGTE applies the GTE predicate on the "last_sync_error" field.
func LastSyncErrorGTE(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldGTE(FieldLastSyncError, v))
}

// LastSyncErrorLT applies the LT predicate on the "last_sync_error" field.
func LastSyncErrorLT(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLT(FieldLastSyncError, v))
}

// LastSyncErrorLTE applies the LTE predicate on the "last_sync_error" field.
func LastSyncErrorLTE(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldLTE(FieldLastSyncError, v))
}

// LastSyncErrorContains applies the Contains predicate on the "last_sync_error" field.
func LastSyncErrorContains(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldContains(FieldLastSyncError, v))
}

// LastSyncErrorHasPrefix applies the HasPrefix predicate on the "last_sync_error" field.
func LastSyncErrorHasPrefix(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldHasPrefix(FieldLastSyncError, v))
}

// LastSyncErrorHasSuffix applies the HasSuffix predicate on the "last_sync_error" field.
func LastSyncErrorHasSuffix(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldHasSuffix(FieldLastSyncError, v))
}

// LastSyncErrorIsNil applies the IsNil predicate on the "last_sync_error" field.
func LastSyncErrorIsNil() predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldIsNull(FieldLastSyncError))
}

// LastSyncErrorNotNil applies the NotNil predicate on the "last_sync_error" field.
func LastSyncErrorNotNil() predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldNotNull(FieldLastSyncError))
}

// LastSyncErrorEqualFold applies the EqualFold predicate on the "last_sync_error" field.
func LastSyncErrorEqualFold(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldEqualFold(FieldLastSyncError, v))
}

// LastSyncErrorContainsFold applies the ContainsFold predicate on the "last_sync_error" field.
func LastSyncErrorContainsFold(v string) predicate.ProposedDate {
	return predicate.ProposedDate(sql.FieldContainsFold(FieldLastSyncError, v))
}

// HasEvent applies the HasEdge predicate on the "event" edge.
func HasEvent() predicate.ProposedDate {
	return predicate.ProposedDate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EventTable, EventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventWith applies the HasEdge predicate on the "event" edge with a given conditions (other predicates).
func HasEventWith(preds ...predicate.Event) predicate.ProposedDate {
	return predicate.ProposedDate(func(s *sql.Selector) {
		step := newEventStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProposedDate) predicate.ProposedDate {
	return predicate.ProposedDate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProposedDate) predicate.ProposedDate {
	return predicate.ProposedDate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProposedDate) predicate.ProposedDate {
	return predicate.ProposedDate(sql.NotPredicates(p))
}
