// Code generated by ent, DO NOT EDIT.

package calendar

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the calendar type in the database.
	Label = "calendar"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldGoogleCalendarID holds the string denoting the google_calendar_id field in the database.
	FieldGoogleCalendarID = "google_calendar_id"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// EdgeUserCalendars holds the string denoting the user_calendars edge name in mutations.
	EdgeUserCalendars = "user_calendars"
	// EdgePrimaryEvents holds the string denoting the primary_events edge name in mutations.
	EdgePrimaryEvents = "primary_events"
	// Table holds the table name of the calendar in the database.
	Table = "calendars"
	// UserCalendarsTable is the table that holds the user_calendars relation/edge.
	UserCalendarsTable = "user_calendars"
	// UserCalendarsInverseTable is the table name for the UserCalendar entity.
	// It exists in this package in order to avoid circular dependency with the "usercalendar" package.
	UserCalendarsInverseTable = "user_calendars"
	// UserCalendarsColumn is the table column denoting the user_calendars relation/edge.
	UserCalendarsColumn = "calendar_id"
	// PrimaryEventsTable is the table that holds the primary_events relation/edge.
	PrimaryEventsTable = "events"
	// PrimaryEventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	PrimaryEventsInverseTable = "events"
	// PrimaryEventsColumn is the table column denoting the primary_events relation/edge.
	PrimaryEventsColumn = "primary_calendar_id"
)

// Columns holds all SQL columns for calendar fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldGoogleCalendarID,
	FieldSummary,
	FieldDescription,
	FieldTimezone,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/runtime"
var (
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Calendar queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByGoogleCalendarID orders the results by the google_calendar_id field.
func ByGoogleCalendarID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoogleCalendarID, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByUserCalendarsCount orders the results by user_calendars count.
func ByUserCalendarsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserCalendarsStep(), opts...)
	}
}

// ByUserCalendars orders the results by user_calendars terms.
func ByUserCalendars(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserCalendarsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPrimaryEventsCount orders the results by primary_events count.
func ByPrimaryEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPrimaryEventsStep(), opts...)
	}
}

// ByPrimaryEvents orders the results by primary_events terms.
func ByPrimaryEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPrimaryEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserCalendarsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserCalendarsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserCalendarsTable, UserCalendarsColumn),
	)
}
func newPrimaryEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PrimaryEventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PrimaryEventsTable, PrimaryEventsColumn),
	)
}
