// Code generated by ent, DO NOT EDIT.

package outboxmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the outboxmessage type in the database.
	Label = "outbox_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldMessageType holds the string denoting the message_type field in the database.
	FieldMessageType = "message_type"
	// FieldAggregateType holds the string denoting the aggregate_type field in the database.
	FieldAggregateType = "aggregate_type"
	// FieldAggregateID holds the string denoting the aggregate_id field in the database.
	FieldAggregateID = "aggregate_id"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldDispatchAttempts holds the string denoting the dispatch_attempts field in the database.
	FieldDispatchAttempts = "dispatch_attempts"
	// FieldAvailableAt holds the string denoting the available_at field in the database.
	FieldAvailableAt = "available_at"
	// FieldDispatchedAt holds the string denoting the dispatched_at field in the database.
	FieldDispatchedAt = "dispatched_at"
	// FieldProcessedAt holds the string denoting the processed_at field in the database.
	FieldProcessedAt = "processed_at"
	// FieldLastDispatchError holds the string denoting the last_dispatch_error field in the database.
	FieldLastDispatchError = "last_dispatch_error"
	// Table holds the table name of the outboxmessage in the database.
	Table = "outbox_messages"
)

// Columns holds all SQL columns for outboxmessage fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldMessageType,
	FieldAggregateType,
	FieldAggregateID,
	FieldPayload,
	FieldDispatchAttempts,
	FieldAvailableAt,
	FieldDispatchedAt,
	FieldProcessedAt,
	FieldLastDispatchError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// MessageTypeValidator is a validator for the "message_type" field. It is called by the builders before save.
	MessageTypeValidator func(string) error
	// AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	AggregateTypeValidator func(string) error
	// DefaultPayload holds the default value on creation for the "payload" field.
	DefaultPayload map[string]interface{}
	// DefaultDispatchAttempts holds the default value on creation for the "dispatch_attempts" field.
	DefaultDispatchAttempts int
	// DispatchAttemptsValidator is a validator for the "dispatch_attempts" field. It is called by the builders before save.
	DispatchAttemptsValidator func(int) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the OutboxMessage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMessageType orders the results by the message_type field.
func ByMessageType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageType, opts...).ToFunc()
}

// ByAggregateType orders the results by the aggregate_type field.
func ByAggregateType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAggregateType, opts...).ToFunc()
}

// ByAggregateID orders the results by the aggregate_id field.
func ByAggregateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAggregateID, opts...).ToFunc()
}

// ByDispatchAttempts orders the results by the dispatch_attempts field.
func ByDispatchAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDispatchAttempts, opts...).ToFunc()
}

// ByAvailableAt orders the results by the available_at field.
func ByAvailableAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableAt, opts...).ToFunc()
}

// ByDispatchedAt orders the results by the dispatched_at field.
func ByDispatchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDispatchedAt, opts...).ToFunc()
}

// ByProcessedAt orders the results by the processed_at field.
func ByProcessedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedAt, opts...).ToFunc()
}

// ByLastDispatchError orders the results by the last_dispatch_error field.
func ByLastDispatchError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDispatchError, opts...).ToFunc()
}
