// Code generated by ent, DO NOT EDIT.

package outboxmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// MessageType applies equality check predicate on the "message_type" field. It's identical to MessageTypeEQ.
func MessageType(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldMessageType, v))
}

// AggregateType applies equality check predicate on the "aggregate_type" field. It's identical to AggregateTypeEQ.
func AggregateType(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldAggregateType, v))
}

// AggregateID applies equality check predicate on the "aggregate_id" field. It's identical to AggregateIDEQ.
func AggregateID(v uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldAggregateID, v))
}

// DispatchAttempts applies equality check predicate on the "dispatch_attempts" field. It's identical to DispatchAttemptsEQ.
func DispatchAttempts(v int) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldDispatchAttempts, v))
}

// AvailableAt applies equality check predicate on the "available_at" field. It's identical to AvailableAtEQ.
func AvailableAt(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldAvailableAt, v))
}

// DispatchedAt applies equality check predicate on the "dispatched_at" field. It's identical to DispatchedAtEQ.
func DispatchedAt(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldDispatchedAt, v))
}

// ProcessedAt applies equality check predicate on the "processed_at" field. It's identical to ProcessedAtEQ.
func ProcessedAt(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldProcessedAt, v))
}

// LastDispatchError applies equality check predicate on the "last_dispatch_error" field. It's identical to LastDispatchErrorEQ.
func LastDispatchError(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldLastDispatchError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLTE(FieldUpdatedAt, v))
}

// MessageTypeEQ applies the EQ predicate on the "message_type" field.
func MessageTypeEQ(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldMessageType, v))
}

// MessageTypeNEQ applies the NEQ predicate on the "message_type" field.
func MessageTypeNEQ(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNEQ(FieldMessageType, v))
}

// MessageTypeIn applies the In predicate on the "message_type" field.
func MessageTypeIn(vs ...string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIn(FieldMessageType, vs...))
}

// MessageTypeNotIn applies the NotIn predicate on the "message_type" field.
func MessageTypeNotIn(vs ...string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotIn(FieldMessageType, vs...))
}

// MessageTypeGT applies the GT predicate on the "message_type" field.
func MessageTypeGT(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGT(FieldMessageType, v))
}

// MessageTypeGTE applies the GTE predicate on the "message_type" field.
func MessageTypeGTE(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGTE(FieldMessageType, v))
}

// MessageTypeLT applies the LT predicate on the "message_type" field.
func MessageTypeLT(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLT(FieldMessageType, v))
}

// MessageTypeLTE applies the LTE predicate on the "message_type" field.
func MessageTypeLTE(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLTE(FieldMessageType, v))
}

// MessageTypeContains applies the Contains predicate on the "message_type" field.
func MessageTypeContains(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldContains(FieldMessageType, v))
}

// MessageTypeHasPrefix applies the HasPrefix predicate on the "message_type" field.
func MessageTypeHasPrefix(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldHasPrefix(FieldMessageType, v))
}

// MessageTypeHasSuffix applies the HasSuffix predicate on the "message_type" field.
func MessageTypeHasSuffix(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldHasSuffix(FieldMessageType, v))
}

// MessageTypeEqualFold applies the EqualFold predicate on the "message_type" field.
func MessageTypeEqualFold(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEqualFold(FieldMessageType, v))
}

// MessageTypeContainsFold applies the ContainsFold predicate on the "message_type" field.
func MessageTypeContainsFold(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldContainsFold(FieldMessageType, v))
}

// AggregateTypeEQ applies the EQ predicate on the "aggregate_type" field.
func AggregateTypeEQ(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldAggregateType, v))
}

// AggregateTypeNEQ applies the NEQ predicate on the "aggregate_type" field.
func AggregateTypeNEQ(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNEQ(FieldAggregateType, v))
}

// AggregateTypeIn applies the In predicate on the "aggregate_type" field.
func AggregateTypeIn(vs ...string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIn(FieldAggregateType, vs...))
}

// AggregateTypeNotIn applies the NotIn predicate on the "aggregate_type" field.
func AggregateTypeNotIn(vs ...string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotIn(FieldAggregateType, vs...))
}

// AggregateTypeGT applies the GT predicate on the "aggregate_type" field.
func AggregateTypeGT(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGT(FieldAggregateType, v))
}

// AggregateTypeGTE applies the GTE predicate on the "aggregate_type" field.
func AggregateTypeGTE(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGTE(FieldAggregateType, v))
}

// AggregateTypeLT applies the LT predicate on the "aggregate_type" field.
func AggregateTypeLT(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLT(FieldAggregateType, v))
}

// AggregateTypeLTE applies the LTE predicate on the "aggregate_type" field.
func AggregateTypeLTE(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLTE(FieldAggregateType, v))
}

// AggregateTypeContains applies the Contains predicate on the "aggregate_type" field.
func AggregateTypeContains(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldContains(FieldAggregateType, v))
}

// AggregateTypeHasPrefix applies the HasPrefix predicate on the "aggregate_type" field.
func AggregateTypeHasPrefix(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldHasPrefix(FieldAggregateType, v))
}

// AggregateTypeHasSuffix applies the HasSuffix predicate on the "aggregate_type" field.
func AggregateTypeHasSuffix(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldHasSuffix(FieldAggregateType, v))
}

// AggregateTypeEqualFold applies the EqualFold predicate on the "aggregate_type" field.
func AggregateTypeEqualFold(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEqualFold(FieldAggregateType, v))
}

// AggregateTypeContainsFold applies the ContainsFold predicate on the "aggregate_type" field.
func AggregateTypeContainsFold(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldContainsFold(FieldAggregateType, v))
}

// AggregateIDEQ applies the EQ predicate on the "aggregate_id" field.
func AggregateIDEQ(v uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldAggregateID, v))
}

// AggregateIDNEQ applies the NEQ predicate on the "aggregate_id" field.
func AggregateIDNEQ(v uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNEQ(FieldAggregateID, v))
}

// AggregateIDIn applies the In predicate on the "aggregate_id" field.
func AggregateIDIn(vs ...uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIn(FieldAggregateID, vs...))
}

// AggregateIDNotIn applies the NotIn predicate on the "aggregate_id" field.
func AggregateIDNotIn(vs ...uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotIn(FieldAggregateID, vs...))
}

// AggregateIDGT applies the GT predicate on the "aggregate_id" field.
func AggregateIDGT(v uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGT(FieldAggregateID, v))
}

// AggregateIDGTE applies the GTE predicate on the "aggregate_id" field.
func AggregateIDGTE(v uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGTE(FieldAggregateID, v))
}

// AggregateIDLT applies the LT predicate on the "aggregate_id" field.
func AggregateIDLT(v uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLT(FieldAggregateID, v))
}

// AggregateIDLTE applies the LTE predicate on the "aggregate_id" field.
func AggregateIDLTE(v uuid.UUID) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLTE(FieldAggregateID, v))
}

// DispatchAttemptsEQ applies the EQ predicate on the "dispatch_attempts" field.
func DispatchAttemptsEQ(v int) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldDispatchAttempts, v))
}

// DispatchAttemptsNEQ applies the NEQ predicate on the "dispatch_attempts" field.
func DispatchAttemptsNEQ(v int) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNEQ(FieldDispatchAttempts, v))
}

// DispatchAttemptsIn applies the In predicate on the "dispatch_attempts" field.
func DispatchAttemptsIn(vs ...int) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIn(FieldDispatchAttempts, vs...))
}

// DispatchAttemptsNotIn applies the NotIn predicate on the "dispatch_attempts" field.
func DispatchAttemptsNotIn(vs ...int) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotIn(FieldDispatchAttempts, vs...))
}

// DispatchAttemptsGT applies the GT predicate on the "dispatch_attempts" field.
func DispatchAttemptsGT(v int) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGT(FieldDispatchAttempts, v))
}

// DispatchAttemptsGTE applies the GTE predicate on the "dispatch_attempts" field.
func DispatchAttemptsGTE(v int) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGTE(FieldDispatchAttempts, v))
}

// DispatchAttemptsLT applies the LT predicate on the "dispatch_attempts" field.
func DispatchAttemptsLT(v int) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLT(FieldDispatchAttempts, v))
}

// DispatchAttemptsLTE applies the LTE predicate on the "dispatch_attempts" field.
func DispatchAttemptsLTE(v int) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLTE(FieldDispatchAttempts, v))
}

// AvailableAtEQ applies the EQ predicate on the "available_at" field.
func AvailableAtEQ(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldAvailableAt, v))
}

// AvailableAtNEQ applies the NEQ predicate on the "available_at" field.
func AvailableAtNEQ(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNEQ(FieldAvailableAt, v))
}

// AvailableAtIn applies the In predicate on the "available_at" field.
func AvailableAtIn(vs ...time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIn(FieldAvailableAt, vs...))
}

// AvailableAtNotIn applies the NotIn predicate on the "available_at" field.
func AvailableAtNotIn(vs ...time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotIn(FieldAvailableAt, vs...))
}

// AvailableAtGT applies the GT predicate on the "available_at" field.
func AvailableAtGT(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGT(FieldAvailableAt, v))
}

// AvailableAtGTE applies the GTE predicate on the "available_at" field.
func AvailableAtGTE(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGTE(FieldAvailableAt, v))
}

// AvailableAtLT applies the LT predicate on the "available_at" field.
func AvailableAtLT(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLT(FieldAvailableAt, v))
}

// AvailableAtLTE applies the LTE predicate on the "available_at" field.
func AvailableAtLTE(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLTE(FieldAvailableAt, v))
}

// DispatchedAtEQ applies the EQ predicate on the "dispatched_at" field.
func DispatchedAtEQ(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldDispatchedAt, v))
}

// DispatchedAtNEQ applies the NEQ predicate on the "dispatched_at" field.
func DispatchedAtNEQ(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNEQ(FieldDispatchedAt, v))
}

// DispatchedAtIn applies the In predicate on the "dispatched_at" field.
func DispatchedAtIn(vs ...time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIn(FieldDispatchedAt, vs...))
}

// DispatchedAtNotIn applies the NotIn predicate on the "dispatched_at" field.
func DispatchedAtNotIn(vs ...time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotIn(FieldDispatchedAt, vs...))
}

// DispatchedAtGT applies the GT predicate on the "dispatched_at" field.
func DispatchedAtGT(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGT(FieldDispatchedAt, v))
}

// DispatchedAtGTE applies the GTE predicate on the "dispatched_at" field.
func DispatchedAtGTE(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGTE(FieldDispatchedAt, v))
}

// DispatchedAtLT applies the LT predicate on the "dispatched_at" field.
func DispatchedAtLT(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLT(FieldDispatchedAt, v))
}

// DispatchedAtLTE applies the LTE predicate on the "dispatched_at" field.
func DispatchedAtLTE(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLTE(FieldDispatchedAt, v))
}

// DispatchedAtIsNil applies the IsNil predicate on the "dispatched_at" field.
func DispatchedAtIsNil() predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIsNull(FieldDispatchedAt))
}

// DispatchedAtNotNil applies the NotNil predicate on the "dispatched_at" field.
func DispatchedAtNotNil() predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotNull(FieldDispatchedAt))
}

// ProcessedAtEQ applies the EQ predicate on the "processed_at" field.
func ProcessedAtEQ(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldProcessedAt, v))
}

// ProcessedAtNEQ applies the NEQ predicate on the "processed_at" field.
func ProcessedAtNEQ(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNEQ(FieldProcessedAt, v))
}

// ProcessedAtIn applies the In predicate on the "processed_at" field.
func ProcessedAtIn(vs ...time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIn(FieldProcessedAt, vs...))
}

// ProcessedAtNotIn applies the NotIn predicate on the "processed_at" field.
func ProcessedAtNotIn(vs ...time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotIn(FieldProcessedAt, vs...))
}

// ProcessedAtGT applies the GT predicate on the "processed_at" field.
func ProcessedAtGT(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGT(FieldProcessedAt, v))
}

// ProcessedAtGTE applies the GTE predicate on the "processed_at" field.
func ProcessedAtGTE(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGTE(FieldProcessedAt, v))
}

// ProcessedAtLT applies the LT predicate on the "processed_at" field.
func ProcessedAtLT(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLT(FieldProcessedAt, v))
}

// ProcessedAtLTE applies the LTE predicate on the "processed_at" field.
func ProcessedAtLTE(v time.Time) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLTE(FieldProcessedAt, v))
}

// ProcessedAtIsNil applies the IsNil predicate on the "processed_at" field.
func ProcessedAtIsNil() predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIsNull(FieldProcessedAt))
}

// ProcessedAtNotNil applies the NotNil predicate on the "processed_at" field.
func ProcessedAtNotNil() predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotNull(FieldProcessedAt))
}

// LastDispatchErrorEQ applies the EQ predicate on the "last_dispatch_error" field.
func LastDispatchErrorEQ(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEQ(FieldLastDispatchError, v))
}

// LastDispatchErrorNEQ applies the NEQ predicate on the "last_dispatch_error" field.
func LastDispatchErrorNEQ(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNEQ(FieldLastDispatchError, v))
}

// LastDispatchErrorIn applies the In predicate on the "last_dispatch_error" field.
func LastDispatchErrorIn(vs ...string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIn(FieldLastDispatchError, vs...))
}

// LastDispatchErrorNotIn applies the NotIn predicate on the "last_dispatch_error" field.
func LastDispatchErrorNotIn(vs ...string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotIn(FieldLastDispatchError, vs...))
}

// LastDispatchErrorGT applies the GT predicate on the "last_dispatch_error" field.
func LastDispatchErrorGT(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGT(FieldLastDispatchError, v))
}

// LastDispatchErrorGTE applies the GTE predicate on the "last_dispatch_error" field.
func LastDispatchErrorGTE(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldGTE(FieldLastDispatchError, v))
}

// LastDispatchErrorLT applies the LT predicate on the "last_dispatch_error" field.
func LastDispatchErrorLT(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLT(FieldLastDispatchError, v))
}

// LastDispatchErrorLTE applies the LTE predicate on the "last_dispatch_error" field.
func LastDispatchErrorLTE(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldLTE(FieldLastDispatchError, v))
}

// LastDispatchErrorContains applies the Contains predicate on the "last_dispatch_error" field.
func LastDispatchErrorContains(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldContains(FieldLastDispatchError, v))
}

// LastDispatchErrorHasPrefix applies the HasPrefix predicate on the "last_dispatch_error" field.
func LastDispatchErrorHasPrefix(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldHasPrefix(FieldLastDispatchError, v))
}

// LastDispatchErrorHasSuffix applies the HasSuffix predicate on the "last_dispatch_error" field.
func LastDispatchErrorHasSuffix(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldHasSuffix(FieldLastDispatchError, v))
}

// LastDispatchErrorIsNil applies the IsNil predicate on the "last_dispatch_error" field.
func LastDispatchErrorIsNil() predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldIsNull(FieldLastDispatchError))
}

// LastDispatchErrorNotNil applies the NotNil predicate on the "last_dispatch_error" field.
func LastDispatchErrorNotNil() predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldNotNull(FieldLastDispatchError))
}

// LastDispatchErrorEqualFold applies the EqualFold predicate on the "last_dispatch_error" field.
func LastDispatchErrorEqualFold(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldEqualFold(FieldLastDispatchError, v))
}

// LastDispatchErrorContainsFold applies the ContainsFold predicate on the "last_dispatch_error" field.
func LastDispatchErrorContainsFold(v string) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.FieldContainsFold(FieldLastDispatchError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OutboxMessage) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OutboxMessage) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OutboxMessage) predicate.OutboxMessage {
	return predicate.OutboxMessage(sql.NotPredicates(p))
}
