// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/calendar"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/event"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/usercalendar"
)

// CalendarCreate is the builder for creating a Calendar entity.
type CalendarCreate struct {
	config
	mutation *CalendarMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (cc *CalendarCreate) SetCreatedAt(t time.Time) *CalendarCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CalendarCreate) SetNillableCreatedAt(t *time.Time) *CalendarCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *CalendarCreate) SetUpdatedAt(t time.Time) *CalendarCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *CalendarCreate) SetNillableUpdatedAt(t *time.Time) *CalendarCreate {
	if t != nil {
		cc.SetUpdatedAt(*t)
	}
	return cc
}

// SetDeletedAt sets the "deleted_at" field.
func (cc *CalendarCreate) SetDeletedAt(t time.Time) *CalendarCreate {
	cc.mutation.SetDeletedAt(t)
	return cc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (cc *CalendarCreate) SetNillableDeletedAt(t *time.Time) *CalendarCreate {
	if t != nil {
		cc.SetDeletedAt(*t)
	}
	return cc
}

// SetGoogleCalendarID sets the "google_calendar_id" field.
func (cc *CalendarCreate) SetGoogleCalendarID(s string) *CalendarCreate {
	cc.mutation.SetGoogleCalendarID(s)
	return cc
}

// SetNillableGoogleCalendarID sets the "google_calendar_id" field if the given value is not nil.
func (cc *CalendarCreate) SetNillableGoogleCalendarID(s *string) *CalendarCreate {
	if s != nil {
		cc.SetGoogleCalendarID(*s)
	}
	return cc
}

// SetSummary sets the "summary" field.
func (cc *CalendarCreate) SetSummary(s string) *CalendarCreate {
	cc.mutation.SetSummary(s)
	return cc
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (cc *CalendarCreate) SetNillableSummary(s *string) *CalendarCreate {
	if s != nil {
		cc.SetSummary(*s)
	}
	return cc
}

// SetDescription sets the "description" field.
func (cc *CalendarCreate) SetDescription(s string) *CalendarCreate {
	cc.mutation.SetDescription(s)
	return cc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (cc *CalendarCreate) SetNillableDescription(s *string) *CalendarCreate {
	if s != nil {
		cc.SetDescription(*s)
	}
	return cc
}

// SetTimezone sets the "timezone" field.
func (cc *CalendarCreate) SetTimezone(s string) *CalendarCreate {
	cc.mutation.SetTimezone(s)
	return cc
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (cc *CalendarCreate) SetNillableTimezone(s *string) *CalendarCreate {
	if s != nil {
		cc.SetTimezone(*s)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CalendarCreate) SetID(u uuid.UUID) *CalendarCreate {
	cc.mutation.SetID(u)
	return cc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (cc *CalendarCreate) SetNillableID(u *uuid.UUID) *CalendarCreate {
	if u != nil {
		cc.SetID(*u)
	}
	return cc
}

// AddUserCalendarIDs adds the "user_calendars" edge to the UserCalendar entity by IDs.
func (cc *CalendarCreate) AddUserCalendarIDs(ids ...uuid.UUID) *CalendarCreate {
	cc.mutation.AddUserCalendarIDs(ids...)
	return cc
}

// AddUserCalendars adds the "user_calendars" edges to the UserCalendar entity.
func (cc *CalendarCreate) AddUserCalendars(u ...*UserCalendar) *CalendarCreate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cc.AddUserCalendarIDs(ids...)
}

// AddPrimaryEventIDs adds the "primary_events" edge to the Event entity by IDs.
func (cc *CalendarCreate) AddPrimaryEventIDs(ids ...uuid.UUID) *CalendarCreate {
	cc.mutation.AddPrimaryEventIDs(ids...)
	return cc
}

// AddPrimaryEvents adds the "primary_events" edges to the Event entity.
func (cc *CalendarCreate) AddPrimaryEvents(e ...*Event) *CalendarCreate {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return cc.AddPrimaryEventIDs(ids...)
}

// Mutation returns the CalendarMutation object of the builder.
func (cc *CalendarCreate) Mutation() *CalendarMutation {
	return cc.mutation
}

// Save creates the Calendar in the database.
func (cc *CalendarCreate) Save(ctx context.Context) (*Calendar, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CalendarCreate) SaveX(ctx context.Context) *Calendar {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CalendarCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CalendarCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CalendarCreate) defaults() {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := calendar.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		v := calendar.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
	if _, ok := cc.mutation.ID(); !ok {
		v := calendar.DefaultID()
		cc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CalendarCreate) check() error {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Calendar.created_at"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Calendar.updated_at"`)}
	}
	return nil
}

func (cc *CalendarCreate) sqlSave(ctx context.Context) (*Calendar, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CalendarCreate) createSpec() (*Calendar, *sqlgraph.CreateSpec) {
	var (
		_node = &Calendar{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(calendar.Table, sqlgraph.NewFieldSpec(calendar.FieldID, field.TypeUUID))
	)
	_spec.Schema = cc.schemaConfig.Calendar
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(calendar.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(calendar.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cc.mutation.DeletedAt(); ok {
		_spec.SetField(calendar.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := cc.mutation.GoogleCalendarID(); ok {
		_spec.SetField(calendar.FieldGoogleCalendarID, field.TypeString, value)
		_node.GoogleCalendarID = &value
	}
	if value, ok := cc.mutation.Summary(); ok {
		_spec.SetField(calendar.FieldSummary, field.TypeString, value)
		_node.Summary = &value
	}
	if value, ok := cc.mutation.Description(); ok {
		_spec.SetField(calendar.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := cc.mutation.Timezone(); ok {
		_spec.SetField(calendar.FieldTimezone, field.TypeString, value)
		_node.Timezone = &value
	}
	if nodes := cc.mutation.UserCalendarsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   calendar.UserCalendarsTable,
			Columns: []string{calendar.UserCalendarsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usercalendar.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = cc.schemaConfig.UserCalendar
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.PrimaryEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   calendar.PrimaryEventsTable,
			Columns: []string{calendar.PrimaryEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = cc.schemaConfig.Event
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CalendarCreateBulk is the builder for creating many Calendar entities in bulk.
type CalendarCreateBulk struct {
	config
	err      error
	builders []*CalendarCreate
}

// Save creates the Calendar entities in the database.
func (ccb *CalendarCreateBulk) Save(ctx context.Context) ([]*Calendar, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Calendar, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CalendarMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CalendarCreateBulk) SaveX(ctx context.Context) []*Calendar {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CalendarCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CalendarCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
