// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/outboxmessage"
)

// OutboxMessageCreate is the builder for creating a OutboxMessage entity.
type OutboxMessageCreate struct {
	config
	mutation *OutboxMessageMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (omc *OutboxMessageCreate) SetCreatedAt(t time.Time) *OutboxMessageCreate {
	omc.mutation.SetCreatedAt(t)
	return omc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (omc *OutboxMessageCreate) SetNillableCreatedAt(t *time.Time) *OutboxMessageCreate {
	if t != nil {
		omc.SetCreatedAt(*t)
	}
	return omc
}

// SetUpdatedAt sets the "updated_at" field.
func (omc *OutboxMessageCreate) SetUpdatedAt(t time.Time) *OutboxMessageCreate {
	omc.mutation.SetUpdatedAt(t)
	return omc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (omc *OutboxMessageCreate) SetNillableUpdatedAt(t *time.Time) *OutboxMessageCreate {
	if t != nil {
		omc.SetUpdatedAt(*t)
	}
	return omc
}

// SetMessageType sets the "message_type" field.
func (omc *OutboxMessageCreate) SetMessageType(s string) *OutboxMessageCreate {
	omc.mutation.SetMessageType(s)
	return omc
}

// SetAggregateType sets the "aggregate_type" field.
func (omc *OutboxMessageCreate) SetAggregateType(s string) *OutboxMessageCreate {
	omc.mutation.SetAggregateType(s)
	return omc
}

// SetAggregateID sets the "aggregate_id" field.
func (omc *OutboxMessageCreate) SetAggregateID(u uuid.UUID) *OutboxMessageCreate {
	omc.mutation.SetAggregateID(u)
	return omc
}

// SetPayload sets the "payload" field.
func (omc *OutboxMessageCreate) SetPayload(m map[string]interface{}) *OutboxMessageCreate {
	omc.mutation.SetPayload(m)
	return omc
}

// SetDispatchAttempts sets the "dispatch_attempts" field.
func (omc *OutboxMessageCreate) SetDispatchAttempts(i int) *OutboxMessageCreate {
	omc.mutation.SetDispatchAttempts(i)
	return omc
}

// SetNillableDispatchAttempts sets the "dispatch_attempts" field if the given value is not nil.
func (omc *OutboxMessageCreate) SetNillableDispatchAttempts(i *int) *OutboxMessageCreate {
	if i != nil {
		omc.SetDispatchAttempts(*i)
	}
	return omc
}

// SetAvailableAt sets the "available_at" field.
func (omc *OutboxMessageCreate) SetAvailableAt(t time.Time) *OutboxMessageCreate {
	omc.mutation.SetAvailableAt(t)
	return omc
}

// SetDispatchedAt sets the "dispatched_at" field.
func (omc *OutboxMessageCreate) SetDispatchedAt(t time.Time) *OutboxMessageCreate {
	omc.mutation.SetDispatchedAt(t)
	return omc
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (omc *OutboxMessageCreate) SetNillableDispatchedAt(t *time.Time) *OutboxMessageCreate {
	if t != nil {
		omc.SetDispatchedAt(*t)
	}
	return omc
}

// SetProcessedAt sets the "processed_at" field.
func (omc *OutboxMessageCreate) SetProcessedAt(t time.Time) *OutboxMessageCreate {
	omc.mutation.SetProcessedAt(t)
	return omc
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (omc *OutboxMessageCreate) SetNillableProcessedAt(t *time.Time) *OutboxMessageCreate {
	if t != nil {
		omc.SetProcessedAt(*t)
	}
	return omc
}

// SetLastDispatchError sets the "last_dispatch_error" field.
func (omc *OutboxMessageCreate) SetLastDispatchError(s string) *OutboxMessageCreate {
	omc.mutation.SetLastDispatchError(s)
	return omc
}

// SetNillableLastDispatchError sets the "last_dispatch_error" field if the given value is not nil.
func (omc *OutboxMessageCreate) SetNillableLastDispatchError(s *string) *OutboxMessageCreate {
	if s != nil {
		omc.SetLastDispatchError(*s)
	}
	return omc
}

// SetID sets the "id" field.
func (omc *OutboxMessageCreate) SetID(u uuid.UUID) *OutboxMessageCreate {
	omc.mutation.SetID(u)
	return omc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (omc *OutboxMessageCreate) SetNillableID(u *uuid.UUID) *OutboxMessageCreate {
	if u != nil {
		omc.SetID(*u)
	}
	return omc
}

// Mutation returns the OutboxMessageMutation object of the builder.
func (omc *OutboxMessageCreate) Mutation() *OutboxMessageMutation {
	return omc.mutation
}

// Save creates the OutboxMessage in the database.
func (omc *OutboxMessageCreate) Save(ctx context.Context) (*OutboxMessage, error) {
	omc.defaults()
	return withHooks(ctx, omc.sqlSave, omc.mutation, omc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (omc *OutboxMessageCreate) SaveX(ctx context.Context) *OutboxMessage {
	v, err := omc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (omc *OutboxMessageCreate) Exec(ctx context.Context) error {
	_, err := omc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omc *OutboxMessageCreate) ExecX(ctx context.Context) {
	if err := omc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (omc *OutboxMessageCreate) defaults() {
	if _, ok := omc.mutation.CreatedAt(); !ok {
		v := outboxmessage.DefaultCreatedAt()
		omc.mutation.SetCreatedAt(v)
	}
	if _, ok := omc.mutation.UpdatedAt(); !ok {
		v := outboxmessage.DefaultUpdatedAt()
		omc.mutation.SetUpdatedAt(v)
	}
	if _, ok := omc.mutation.Payload(); !ok {
		v := outboxmessage.DefaultPayload
		omc.mutation.SetPayload(v)
	}
	if _, ok := omc.mutation.DispatchAttempts(); !ok {
		v := outboxmessage.DefaultDispatchAttempts
		omc.mutation.SetDispatchAttempts(v)
	}
	if _, ok := omc.mutation.ID(); !ok {
		v := outboxmessage.DefaultID()
		omc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (omc *OutboxMessageCreate) check() error {
	if _, ok := omc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OutboxMessage.created_at"`)}
	}
	if _, ok := omc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OutboxMessage.updated_at"`)}
	}
	if _, ok := omc.mutation.MessageType(); !ok {
		return &ValidationError{Name: "message_type", err: errors.New(`ent: missing required field "OutboxMessage.message_type"`)}
	}
	if v, ok := omc.mutation.MessageType(); ok {
		if err := outboxmessage.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.message_type": %w`, err)}
		}
	}
	if _, ok := omc.mutation.AggregateType(); !ok {
		return &ValidationError{Name: "aggregate_type", err: errors.New(`ent: missing required field "OutboxMessage.aggregate_type"`)}
	}
	if v, ok := omc.mutation.AggregateType(); ok {
		if err := outboxmessage.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.aggregate_type": %w`, err)}
		}
	}
	if _, ok := omc.mutation.AggregateID(); !ok {
		return &ValidationError{Name: "aggregate_id", err: errors.New(`ent: missing required field "OutboxMessage.aggregate_id"`)}
	}
	if _, ok := omc.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "OutboxMessage.payload"`)}
	}
	if _, ok := omc.mutation.DispatchAttempts(); !ok {
		return &ValidationError{Name: "dispatch_attempts", err: errors.New(`ent: missing required field "OutboxMessage.dispatch_attempts"`)}
	}
	if v, ok := omc.mutation.DispatchAttempts(); ok {
		if err := outboxmessage.DispatchAttemptsValidator(v); err != nil {
			return &ValidationError{Name: "dispatch_attempts", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.dispatch_attempts": %w`, err)}
		}
	}
	if _, ok := omc.mutation.AvailableAt(); !ok {
		return &ValidationError{Name: "available_at", err: errors.New(`ent: missing required field "OutboxMessage.available_at"`)}
	}
	return nil
}

func (omc *OutboxMessageCreate) sqlSave(ctx context.Context) (*OutboxMessage, error) {
	if err := omc.check(); err != nil {
		return nil, err
	}
	_node, _spec := omc.createSpec()
	if err := sqlgraph.CreateNode(ctx, omc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	omc.mutation.id = &_node.ID
	omc.mutation.done = true
	return _node, nil
}

func (omc *OutboxMessageCreate) createSpec() (*OutboxMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &OutboxMessage{config: omc.config}
		_spec = sqlgraph.NewCreateSpec(outboxmessage.Table, sqlgraph.NewFieldSpec(outboxmessage.FieldID, field.TypeUUID))
	)
	_spec.Schema = omc.schemaConfig.OutboxMessage
	if id, ok := omc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := omc.mutation.CreatedAt(); ok {
		_spec.SetField(outboxmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := omc.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxmessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := omc.mutation.MessageType(); ok {
		_spec.SetField(outboxmessage.FieldMessageType, field.TypeString, value)
		_node.MessageType = value
	}
	if value, ok := omc.mutation.AggregateType(); ok {
		_spec.SetField(outboxmessage.FieldAggregateType, field.TypeString, value)
		_node.AggregateType = value
	}
	if value, ok := omc.mutation.AggregateID(); ok {
		_spec.SetField(outboxmessage.FieldAggregateID, field.TypeUUID, value)
		_node.AggregateID = value
	}
	if value, ok := omc.mutation.Payload(); ok {
		_spec.SetField(outboxmessage.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := omc.mutation.DispatchAttempts(); ok {
		_spec.SetField(outboxmessage.FieldDispatchAttempts, field.TypeInt, value)
		_node.DispatchAttempts = value
	}
	if value, ok := omc.mutation.AvailableAt(); ok {
		_spec.SetField(outboxmessage.FieldAvailableAt, field.TypeTime, value)
		_node.AvailableAt = value
	}
	if value, ok := omc.mutation.DispatchedAt(); ok {
		_spec.SetField(outboxmessage.FieldDispatchedAt, field.TypeTime, value)
		_node.DispatchedAt = &value
	}
	if value, ok := omc.mutation.ProcessedAt(); ok {
		_spec.SetField(outboxmessage.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if value, ok := omc.mutation.LastDispatchError(); ok {
		_spec.SetField(outboxmessage.FieldLastDispatchError, field.TypeString, value)
		_node.LastDispatchError = &value
	}
	return _node, _spec
}

// OutboxMessageCreateBulk is the builder for creating many OutboxMessage entities in bulk.
type OutboxMessageCreateBulk struct {
	config
	err      error
	builders []*OutboxMessageCreate
}

// Save creates the OutboxMessage entities in the database.
func (omcb *OutboxMessageCreateBulk) Save(ctx context.Context) ([]*OutboxMessage, error) {
	if omcb.err != nil {
		return nil, omcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(omcb.builders))
	nodes := make([]*OutboxMessage, len(omcb.builders))
	mutators := make([]Mutator, len(omcb.builders))
	for i := range omcb.builders {
		func(i int, root context.Context) {
			builder := omcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OutboxMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, omcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, omcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, omcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (omcb *OutboxMessageCreateBulk) SaveX(ctx context.Context) []*OutboxMessage {
	v, err := omcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (omcb *OutboxMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := omcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omcb *OutboxMessageCreateBulk) ExecX(ctx context.Context) {
	if err := omcb.Exec(ctx); err != nil {
		panic(err)
	}
}
