// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/outboxmessage"
)

// OutboxMessage is the model entity for the OutboxMessage schema.
type OutboxMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// MessageType holds the value of the "message_type" field.
	MessageType string `json:"message_type,omitempty"`
	// AggregateType holds the value of the "aggregate_type" field.
	AggregateType string `json:"aggregate_type,omitempty"`
	// AggregateID holds the value of the "aggregate_id" field.
	AggregateID uuid.UUID `json:"aggregate_id,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// DispatchAttempts holds the value of the "dispatch_attempts" field.
	DispatchAttempts int `json:"dispatch_attempts,omitempty"`
	// AvailableAt holds the value of the "available_at" field.
	AvailableAt time.Time `json:"available_at,omitempty"`
	// DispatchedAt holds the value of the "dispatched_at" field.
	DispatchedAt *time.Time `json:"dispatched_at,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// LastDispatchError holds the value of the "last_dispatch_error" field.
	LastDispatchError *string `json:"last_dispatch_error,omitempty"`
	selectValues      sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OutboxMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outboxmessage.FieldPayload:
			values[i] = new([]byte)
		case outboxmessage.FieldDispatchAttempts:
			values[i] = new(sql.NullInt64)
		case outboxmessage.FieldMessageType, outboxmessage.FieldAggregateType, outboxmessage.FieldLastDispatchError:
			values[i] = new(sql.NullString)
		case outboxmessage.FieldCreatedAt, outboxmessage.FieldUpdatedAt, outboxmessage.FieldAvailableAt, outboxmessage.FieldDispatchedAt, outboxmessage.FieldProcessedAt:
			values[i] = new(sql.NullTime)
		case outboxmessage.FieldID, outboxmessage.FieldAggregateID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OutboxMessage fields.
func (om *OutboxMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outboxmessage.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				om.ID = *value
			}
		case outboxmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				om.CreatedAt = value.Time
			}
		case outboxmessage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				om.UpdatedAt = value.Time
			}
		case outboxmessage.FieldMessageType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_type", values[i])
			} else if value.Valid {
				om.MessageType = value.String
			}
		case outboxmessage.FieldAggregateType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aggregate_type", values[i])
			} else if value.Valid {
				om.AggregateType = value.String
			}
		case outboxmessage.FieldAggregateID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field aggregate_id", values[i])
			} else if value != nil {
				om.AggregateID = *value
			}
		case outboxmessage.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &om.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case outboxmessage.FieldDispatchAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field dispatch_attempts", values[i])
			} else if value.Valid {
				om.DispatchAttempts = int(value.Int64)
			}
		case outboxmessage.FieldAvailableAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field available_at", values[i])
			} else if value.Valid {
				om.AvailableAt = value.Time
			}
		case outboxmessage.FieldDispatchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dispatched_at", values[i])
			} else if value.Valid {
				om.DispatchedAt = new(time.Time)
				*om.DispatchedAt = value.Time
			}
		case outboxmessage.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				om.ProcessedAt = new(time.Time)
				*om.ProcessedAt = value.Time
			}
		case outboxmessage.FieldLastDispatchError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_dispatch_error", values[i])
			} else if value.Valid {
				om.LastDispatchError = new(string)
				*om.LastDispatchError = value.String
			}
		default:
			om.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OutboxMessage.
// This includes values selected through modifiers, order, etc.
func (om *OutboxMessage) Value(name string) (ent.Value, error) {
	return om.selectValues.Get(name)
}

// Update returns a builder for updating this OutboxMessage.
// Note that you need to call OutboxMessage.Unwrap() before calling this method if this OutboxMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (om *OutboxMessage) Update() *OutboxMessageUpdateOne {
	return NewOutboxMessageClient(om.config).UpdateOne(om)
}

// Unwrap unwraps the OutboxMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (om *OutboxMessage) Unwrap() *OutboxMessage {
	_tx, ok := om.config.driver.(*txDriver)
	if !ok {
		panic("ent: OutboxMessage is not a transactional entity")
	}
	om.config.driver = _tx.drv
	return om
}

// String implements the fmt.Stringer.
func (om *OutboxMessage) String() string {
	var builder strings.Builder
	builder.WriteString("OutboxMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", om.ID))
	builder.WriteString("created_at=")
	builder.WriteString(om.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(om.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("message_type=")
	builder.WriteString(om.MessageType)
	builder.WriteString(", ")
	builder.WriteString("aggregate_type=")
	builder.WriteString(om.AggregateType)
	builder.WriteString(", ")
	builder.WriteString("aggregate_id=")
	builder.WriteString(fmt.Sprintf("%v", om.AggregateID))
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", om.Payload))
	builder.WriteString(", ")
	builder.WriteString("dispatch_attempts=")
	builder.WriteString(fmt.Sprintf("%v", om.DispatchAttempts))
	builder.WriteString(", ")
	builder.WriteString("available_at=")
	builder.WriteString(om.AvailableAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := om.DispatchedAt; v != nil {
		builder.WriteString("dispatched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := om.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := om.LastDispatchError; v != nil {
		builder.WriteString("last_dispatch_error=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// OutboxMessages is a parsable slice of OutboxMessage.
type OutboxMessages []*OutboxMessage
