// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/internal"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/outboxmessage"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/predicate"
)

// OutboxMessageUpdate is the builder for updating OutboxMessage entities.
type OutboxMessageUpdate struct {
	config
	hooks    []Hook
	mutation *OutboxMessageMutation
}

// Where appends a list predicates to the OutboxMessageUpdate builder.
func (omu *OutboxMessageUpdate) Where(ps ...predicate.OutboxMessage) *OutboxMessageUpdate {
	omu.mutation.Where(ps...)
	return omu
}

// SetUpdatedAt sets the "updated_at" field.
func (omu *OutboxMessageUpdate) SetUpdatedAt(t time.Time) *OutboxMessageUpdate {
	omu.mutation.SetUpdatedAt(t)
	return omu
}

// SetMessageType sets the "message_type" field.
func (omu *OutboxMessageUpdate) SetMessageType(s string) *OutboxMessageUpdate {
	omu.mutation.SetMessageType(s)
	return omu
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (omu *OutboxMessageUpdate) SetNillableMessageType(s *string) *OutboxMessageUpdate {
	if s != nil {
		omu.SetMessageType(*s)
	}
	return omu
}

// SetAggregateType sets the "aggregate_type" field.
func (omu *OutboxMessageUpdate) SetAggregateType(s string) *OutboxMessageUpdate {
	omu.mutation.SetAggregateType(s)
	return omu
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (omu *OutboxMessageUpdate) SetNillableAggregateType(s *string) *OutboxMessageUpdate {
	if s != nil {
		omu.SetAggregateType(*s)
	}
	return omu
}

// SetAggregateID sets the "aggregate_id" field.
func (omu *OutboxMessageUpdate) SetAggregateID(u uuid.UUID) *OutboxMessageUpdate {
	omu.mutation.SetAggregateID(u)
	return omu
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (omu *OutboxMessageUpdate) SetNillableAggregateID(u *uuid.UUID) *OutboxMessageUpdate {
	if u != nil {
		omu.SetAggregateID(*u)
	}
	return omu
}

// SetPayload sets the "payload" field.
func (omu *OutboxMessageUpdate) SetPayload(m map[string]interface{}) *OutboxMessageUpdate {
	omu.mutation.SetPayload(m)
	return omu
}

// SetDispatchAttempts sets the "dispatch_attempts" field.
func (omu *OutboxMessageUpdate) SetDispatchAttempts(i int) *OutboxMessageUpdate {
	omu.mutation.ResetDispatchAttempts()
	omu.mutation.SetDispatchAttempts(i)
	return omu
}

// SetNillableDispatchAttempts sets the "dispatch_attempts" field if the given value is not nil.
func (omu *OutboxMessageUpdate) SetNillableDispatchAttempts(i *int) *OutboxMessageUpdate {
	if i != nil {
		omu.SetDispatchAttempts(*i)
	}
	return omu
}

// AddDispatchAttempts adds i to the "dispatch_attempts" field.
func (omu *OutboxMessageUpdate) AddDispatchAttempts(i int) *OutboxMessageUpdate {
	omu.mutation.AddDispatchAttempts(i)
	return omu
}

// SetAvailableAt sets the "available_at" field.
func (omu *OutboxMessageUpdate) SetAvailableAt(t time.Time) *OutboxMessageUpdate {
	omu.mutation.SetAvailableAt(t)
	return omu
}

// SetNillableAvailableAt sets the "available_at" field if the given value is not nil.
func (omu *OutboxMessageUpdate) SetNillableAvailableAt(t *time.Time) *OutboxMessageUpdate {
	if t != nil {
		omu.SetAvailableAt(*t)
	}
	return omu
}

// SetDispatchedAt sets the "dispatched_at" field.
func (omu *OutboxMessageUpdate) SetDispatchedAt(t time.Time) *OutboxMessageUpdate {
	omu.mutation.SetDispatchedAt(t)
	return omu
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (omu *OutboxMessageUpdate) SetNillableDispatchedAt(t *time.Time) *OutboxMessageUpdate {
	if t != nil {
		omu.SetDispatchedAt(*t)
	}
	return omu
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (omu *OutboxMessageUpdate) ClearDispatchedAt() *OutboxMessageUpdate {
	omu.mutation.ClearDispatchedAt()
	return omu
}

// SetProcessedAt sets the "processed_at" field.
func (omu *OutboxMessageUpdate) SetProcessedAt(t time.Time) *OutboxMessageUpdate {
	omu.mutation.SetProcessedAt(t)
	return omu
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (omu *OutboxMessageUpdate) SetNillableProcessedAt(t *time.Time) *OutboxMessageUpdate {
	if t != nil {
		omu.SetProcessedAt(*t)
	}
	return omu
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (omu *OutboxMessageUpdate) ClearProcessedAt() *OutboxMessageUpdate {
	omu.mutation.ClearProcessedAt()
	return omu
}

// SetLastDispatchError sets the "last_dispatch_error" field.
func (omu *OutboxMessageUpdate) SetLastDispatchError(s string) *OutboxMessageUpdate {
	omu.mutation.SetLastDispatchError(s)
	return omu
}

// SetNillableLastDispatchError sets the "last_dispatch_error" field if the given value is not nil.
func (omu *OutboxMessageUpdate) SetNillableLastDispatchError(s *string) *OutboxMessageUpdate {
	if s != nil {
		omu.SetLastDispatchError(*s)
	}
	return omu
}

// ClearLastDispatchError clears the value of the "last_dispatch_error" field.
func (omu *OutboxMessageUpdate) ClearLastDispatchError() *OutboxMessageUpdate {
	omu.mutation.ClearLastDispatchError()
	return omu
}

// Mutation returns the OutboxMessageMutation object of the builder.
func (omu *OutboxMessageUpdate) Mutation() *OutboxMessageMutation {
	return omu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (omu *OutboxMessageUpdate) Save(ctx context.Context) (int, error) {
	omu.defaults()
	return withHooks(ctx, omu.sqlSave, omu.mutation, omu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (omu *OutboxMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := omu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (omu *OutboxMessageUpdate) Exec(ctx context.Context) error {
	_, err := omu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omu *OutboxMessageUpdate) ExecX(ctx context.Context) {
	if err := omu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (omu *OutboxMessageUpdate) defaults() {
	if _, ok := omu.mutation.UpdatedAt(); !ok {
		v := outboxmessage.UpdateDefaultUpdatedAt()
		omu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (omu *OutboxMessageUpdate) check() error {
	if v, ok := omu.mutation.MessageType(); ok {
		if err := outboxmessage.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.message_type": %w`, err)}
		}
	}
	if v, ok := omu.mutation.AggregateType(); ok {
		if err := outboxmessage.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.aggregate_type": %w`, err)}
		}
	}
	if v, ok := omu.mutation.DispatchAttempts(); ok {
		if err := outboxmessage.DispatchAttemptsValidator(v); err != nil {
			return &ValidationError{Name: "dispatch_attempts", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.dispatch_attempts": %w`, err)}
		}
	}
	return nil
}

func (omu *OutboxMessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := omu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(outboxmessage.Table, outboxmessage.Columns, sqlgraph.NewFieldSpec(outboxmessage.FieldID, field.TypeUUID))
	if ps := omu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := omu.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := omu.mutation.MessageType(); ok {
		_spec.SetField(outboxmessage.FieldMessageType, field.TypeString, value)
	}
	if value, ok := omu.mutation.AggregateType(); ok {
		_spec.SetField(outboxmessage.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := omu.mutation.AggregateID(); ok {
		_spec.SetField(outboxmessage.FieldAggregateID, field.TypeUUID, value)
	}
	if value, ok := omu.mutation.Payload(); ok {
		_spec.SetField(outboxmessage.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := omu.mutation.DispatchAttempts(); ok {
		_spec.SetField(outboxmessage.FieldDispatchAttempts, field.TypeInt, value)
	}
	if value, ok := omu.mutation.AddedDispatchAttempts(); ok {
		_spec.AddField(outboxmessage.FieldDispatchAttempts, field.TypeInt, value)
	}
	if value, ok := omu.mutation.AvailableAt(); ok {
		_spec.SetField(outboxmessage.FieldAvailableAt, field.TypeTime, value)
	}
	if value, ok := omu.mutation.DispatchedAt(); ok {
		_spec.SetField(outboxmessage.FieldDispatchedAt, field.TypeTime, value)
	}
	if omu.mutation.DispatchedAtCleared() {
		_spec.ClearField(outboxmessage.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := omu.mutation.ProcessedAt(); ok {
		_spec.SetField(outboxmessage.FieldProcessedAt, field.TypeTime, value)
	}
	if omu.mutation.ProcessedAtCleared() {
		_spec.ClearField(outboxmessage.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := omu.mutation.LastDispatchError(); ok {
		_spec.SetField(outboxmessage.FieldLastDispatchError, field.TypeString, value)
	}
	if omu.mutation.LastDispatchErrorCleared() {
		_spec.ClearField(outboxmessage.FieldLastDispatchError, field.TypeString)
	}
	_spec.Node.Schema = omu.schemaConfig.OutboxMessage
	ctx = internal.NewSchemaConfigContext(ctx, omu.schemaConfig)
	if n, err = sqlgraph.UpdateNodes(ctx, omu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	omu.mutation.done = true
	return n, nil
}

// OutboxMessageUpdateOne is the builder for updating a single OutboxMessage entity.
type OutboxMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutboxMessageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (omuo *OutboxMessageUpdateOne) SetUpdatedAt(t time.Time) *OutboxMessageUpdateOne {
	omuo.mutation.SetUpdatedAt(t)
	return omuo
}

// SetMessageType sets the "message_type" field.
func (omuo *OutboxMessageUpdateOne) SetMessageType(s string) *OutboxMessageUpdateOne {
	omuo.mutation.SetMessageType(s)
	return omuo
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (omuo *OutboxMessageUpdateOne) SetNillableMessageType(s *string) *OutboxMessageUpdateOne {
	if s != nil {
		omuo.SetMessageType(*s)
	}
	return omuo
}

// SetAggregateType sets the "aggregate_type" field.
func (omuo *OutboxMessageUpdateOne) SetAggregateType(s string) *OutboxMessageUpdateOne {
	omuo.mutation.SetAggregateType(s)
	return omuo
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (omuo *OutboxMessageUpdateOne) SetNillableAggregateType(s *string) *OutboxMessageUpdateOne {
	if s != nil {
		omuo.SetAggregateType(*s)
	}
	return omuo
}

// SetAggregateID sets the "aggregate_id" field.
func (omuo *OutboxMessageUpdateOne) SetAggregateID(u uuid.UUID) *OutboxMessageUpdateOne {
	omuo.mutation.SetAggregateID(u)
	return omuo
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (omuo *OutboxMessageUpdateOne) SetNillableAggregateID(u *uuid.UUID) *OutboxMessageUpdateOne {
	if u != nil {
		omuo.SetAggregateID(*u)
	}
	return omuo
}

// SetPayload sets the "payload" field.
func (omuo *OutboxMessageUpdateOne) SetPayload(m map[string]interface{}) *OutboxMessageUpdateOne {
	omuo.mutation.SetPayload(m)
	return omuo
}

// SetDispatchAttempts sets the "dispatch_attempts" field.
func (omuo *OutboxMessageUpdateOne) SetDispatchAttempts(i int) *OutboxMessageUpdateOne {
	omuo.mutation.ResetDispatchAttempts()
	omuo.mutation.SetDispatchAttempts(i)
	return omuo
}

// SetNillableDispatchAttempts sets the "dispatch_attempts" field if the given value is not nil.
func (omuo *OutboxMessageUpdateOne) SetNillableDispatchAttempts(i *int) *OutboxMessageUpdateOne {
	if i != nil {
		omuo.SetDispatchAttempts(*i)
	}
	return omuo
}

// AddDispatchAttempts adds i to the "dispatch_attempts" field.
func (omuo *OutboxMessageUpdateOne) AddDispatchAttempts(i int) *OutboxMessageUpdateOne {
	omuo.mutation.AddDispatchAttempts(i)
	return omuo
}

// SetAvailableAt sets the "available_at" field.
func (omuo *OutboxMessageUpdateOne) SetAvailableAt(t time.Time) *OutboxMessageUpdateOne {
	omuo.mutation.SetAvailableAt(t)
	return omuo
}

// SetNillableAvailableAt sets the "available_at" field if the given value is not nil.
func (omuo *OutboxMessageUpdateOne) SetNillableAvailableAt(t *time.Time) *OutboxMessageUpdateOne {
	if t != nil {
		omuo.SetAvailableAt(*t)
	}
	return omuo
}

// SetDispatchedAt sets the "dispatched_at" field.
func (omuo *OutboxMessageUpdateOne) SetDispatchedAt(t time.Time) *OutboxMessageUpdateOne {
	omuo.mutation.SetDispatchedAt(t)
	return omuo
}

// SetNillableDispatchedAt sets the "dispatched_at" field if the given value is not nil.
func (omuo *OutboxMessageUpdateOne) SetNillableDispatchedAt(t *time.Time) *OutboxMessageUpdateOne {
	if t != nil {
		omuo.SetDispatchedAt(*t)
	}
	return omuo
}

// ClearDispatchedAt clears the value of the "dispatched_at" field.
func (omuo *OutboxMessageUpdateOne) ClearDispatchedAt() *OutboxMessageUpdateOne {
	omuo.mutation.ClearDispatchedAt()
	return omuo
}

// SetProcessedAt sets the "processed_at" field.
func (omuo *OutboxMessageUpdateOne) SetProcessedAt(t time.Time) *OutboxMessageUpdateOne {
	omuo.mutation.SetProcessedAt(t)
	return omuo
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (omuo *OutboxMessageUpdateOne) SetNillableProcessedAt(t *time.Time) *OutboxMessageUpdateOne {
	if t != nil {
		omuo.SetProcessedAt(*t)
	}
	return omuo
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (omuo *OutboxMessageUpdateOne) ClearProcessedAt() *OutboxMessageUpdateOne {
	omuo.mutation.ClearProcessedAt()
	return omuo
}

// SetLastDispatchError sets the "last_dispatch_error" field.
func (omuo *OutboxMessageUpdateOne) SetLastDispatchError(s string) *OutboxMessageUpdateOne {
	omuo.mutation.SetLastDispatchError(s)
	return omuo
}

// SetNillableLastDispatchError sets the "last_dispatch_error" field if the given value is not nil.
func (omuo *OutboxMessageUpdateOne) SetNillableLastDispatchError(s *string) *OutboxMessageUpdateOne {
	if s != nil {
		omuo.SetLastDispatchError(*s)
	}
	return omuo
}

// ClearLastDispatchError clears the value of the "last_dispatch_error" field.
func (omuo *OutboxMessageUpdateOne) ClearLastDispatchError() *OutboxMessageUpdateOne {
	omuo.mutation.ClearLastDispatchError()
	return omuo
}

// Mutation returns the OutboxMessageMutation object of the builder.
func (omuo *OutboxMessageUpdateOne) Mutation() *OutboxMessageMutation {
	return omuo.mutation
}

// Where appends a list predicates to the OutboxMessageUpdate builder.
func (omuo *OutboxMessageUpdateOne) Where(ps ...predicate.OutboxMessage) *OutboxMessageUpdateOne {
	omuo.mutation.Where(ps...)
	return omuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (omuo *OutboxMessageUpdateOne) Select(field string, fields ...string) *OutboxMessageUpdateOne {
	omuo.fields = append([]string{field}, fields...)
	return omuo
}

// Save executes the query and returns the updated OutboxMessage entity.
func (omuo *OutboxMessageUpdateOne) Save(ctx context.Context) (*OutboxMessage, error) {
	omuo.defaults()
	return withHooks(ctx, omuo.sqlSave, omuo.mutation, omuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (omuo *OutboxMessageUpdateOne) SaveX(ctx context.Context) *OutboxMessage {
	node, err := omuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (omuo *OutboxMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := omuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omuo *OutboxMessageUpdateOne) ExecX(ctx context.Context) {
	if err := omuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (omuo *OutboxMessageUpdateOne) defaults() {
	if _, ok := omuo.mutation.UpdatedAt(); !ok {
		v := outboxmessage.UpdateDefaultUpdatedAt()
		omuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (omuo *OutboxMessageUpdateOne) check() error {
	if v, ok := omuo.mutation.MessageType(); ok {
		if err := outboxmessage.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.message_type": %w`, err)}
		}
	}
	if v, ok := omuo.mutation.AggregateType(); ok {
		if err := outboxmessage.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.aggregate_type": %w`, err)}
		}
	}
	if v, ok := omuo.mutation.DispatchAttempts(); ok {
		if err := outboxmessage.DispatchAttemptsValidator(v); err != nil {
			return &ValidationError{Name: "dispatch_attempts", err: fmt.Errorf(`ent: validator failed for field "OutboxMessage.dispatch_attempts": %w`, err)}
		}
	}
	return nil
}

func (omuo *OutboxMessageUpdateOne) sqlSave(ctx context.Context) (_node *OutboxMessage, err error) {
	if err := omuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(outboxmessage.Table, outboxmessage.Columns, sqlgraph.NewFieldSpec(outboxmessage.FieldID, field.TypeUUID))
	id, ok := omuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OutboxMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := omuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outboxmessage.FieldID)
		for _, f := range fields {
			if !outboxmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outboxmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := omuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := omuo.mutation.UpdatedAt(); ok {
		_spec.SetField(outboxmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := omuo.mutation.MessageType(); ok {
		_spec.SetField(outboxmessage.FieldMessageType, field.TypeString, value)
	}
	if value, ok := omuo.mutation.AggregateType(); ok {
		_spec.SetField(outboxmessage.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := omuo.mutation.AggregateID(); ok {
		_spec.SetField(outboxmessage.FieldAggregateID, field.TypeUUID, value)
	}
	if value, ok := omuo.mutation.Payload(); ok {
		_spec.SetField(outboxmessage.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := omuo.mutation.DispatchAttempts(); ok {
		_spec.SetField(outboxmessage.FieldDispatchAttempts, field.TypeInt, value)
	}
	if value, ok := omuo.mutation.AddedDispatchAttempts(); ok {
		_spec.AddField(outboxmessage.FieldDispatchAttempts, field.TypeInt, value)
	}
	if value, ok := omuo.mutation.AvailableAt(); ok {
		_spec.SetField(outboxmessage.FieldAvailableAt, field.TypeTime, value)
	}
	if value, ok := omuo.mutation.DispatchedAt(); ok {
		_spec.SetField(outboxmessage.FieldDispatchedAt, field.TypeTime, value)
	}
	if omuo.mutation.DispatchedAtCleared() {
		_spec.ClearField(outboxmessage.FieldDispatchedAt, field.TypeTime)
	}
	if value, ok := omuo.mutation.ProcessedAt(); ok {
		_spec.SetField(outboxmessage.FieldProcessedAt, field.TypeTime, value)
	}
	if omuo.mutation.ProcessedAtCleared() {
		_spec.ClearField(outboxmessage.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := omuo.mutation.LastDispatchError(); ok {
		_spec.SetField(outboxmessage.FieldLastDispatchError, field.TypeString, value)
	}
	if omuo.mutation.LastDispatchErrorCleared() {
		_spec.ClearField(outboxmessage.FieldLastDispatchError, field.TypeString)
	}
	_spec.Node.Schema = omuo.schemaConfig.OutboxMessage
	ctx = internal.NewSchemaConfigContext(ctx, omuo.schemaConfig)
	_node = &OutboxMessage{config: omuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, omuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	omuo.mutation.done = true
	return _node, nil
}
