// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/internal"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/predicate"
	"github.com/koo-arch/adjusta-backend/internal/infrastructure/ent/usercalendar"
)

// UserCalendarDelete is the builder for deleting a UserCalendar entity.
type UserCalendarDelete struct {
	config
	hooks    []Hook
	mutation *UserCalendarMutation
}

// Where appends a list predicates to the UserCalendarDelete builder.
func (ucd *UserCalendarDelete) Where(ps ...predicate.UserCalendar) *UserCalendarDelete {
	ucd.mutation.Where(ps...)
	return ucd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ucd *UserCalendarDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ucd.sqlExec, ucd.mutation, ucd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ucd *UserCalendarDelete) ExecX(ctx context.Context) int {
	n, err := ucd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ucd *UserCalendarDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usercalendar.Table, sqlgraph.NewFieldSpec(usercalendar.FieldID, field.TypeUUID))
	_spec.Node.Schema = ucd.schemaConfig.UserCalendar
	ctx = internal.NewSchemaConfigContext(ctx, ucd.schemaConfig)
	if ps := ucd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ucd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ucd.mutation.done = true
	return affected, err
}

// UserCalendarDeleteOne is the builder for deleting a single UserCalendar entity.
type UserCalendarDeleteOne struct {
	ucd *UserCalendarDelete
}

// Where appends a list predicates to the UserCalendarDelete builder.
func (ucdo *UserCalendarDeleteOne) Where(ps ...predicate.UserCalendar) *UserCalendarDeleteOne {
	ucdo.ucd.mutation.Where(ps...)
	return ucdo
}

// Exec executes the deletion query.
func (ucdo *UserCalendarDeleteOne) Exec(ctx context.Context) error {
	n, err := ucdo.ucd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usercalendar.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ucdo *UserCalendarDeleteOne) ExecX(ctx context.Context) {
	if err := ucdo.Exec(ctx); err != nil {
		panic(err)
	}
}
